### ISSUE TITLE
BackstopJS Cannot Generate Reports

### ISSUE THREAD

**Issue by KITSDominicWhite** [garris/BackstopJS#1027]
Running multiple scenarios on BackstopJS, it seems to not generate a report for some of the options: 

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: There are some read requests waitng on finished stream
    at module.exports.ChunkStream._end (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:100:7)
    at module.exports.ChunkStream.end (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:86:10)
    at exports.PNG.PNG.end (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/png.js:97:16)
    at ReadStream.onend (_stream_readable.js:595:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at ReadStream.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^
```

BackstopJS version: 3.9.2

Base.js:

```
module.exports = {
  onBeforeScript: 'puppet/onBefore.js',
  onReadyScript: 'puppet/onReady.js',
  report: ['CI'],
  engine: 'puppeteer',
  engineFlags: [],
  engineOptions: {
    args: ['--no-sandbox'],
  },
  asyncCaptureLimit: 5,
  asyncCompareLimit: 50,
  debug: false,
  debugWindow: false,
};
```

This backstop.js file works: 

```
const scenarios = require('./scenarios');
const base = require('./base');
const paths = require('./paths');

module.exports = {
  id: 'backstop_320',
  viewports: [
    {
      label: '320',
      width: 320,
      height: 768,
    },
  ],
  scenarios,
  paths: paths('320'),
  ...base,
};
```

This doesn't:

```
const scenarios = require('./scenarios');
const base = require('./base');
const paths = require('./paths');

module.exports = {
  id: 'backstop_479',
  viewports: [
    {
      label: '479',
      width: 479,
      height: 768,
    },
  ],
  scenarios,
  paths: paths('479'),
  ...base,
};
```

We run the scenarios like so: 

```
    "visual:1920": "./node_modules/.bin/backstop test --docker --config=backstop_data/backstop-1920.js",
    "visual:1400": "./node_modules/.bin/backstop test --docker --config=backstop_data/backstop-1400.js",
    "visual:1020": "./node_modules/.bin/backstop test --docker --config=backstop_data/backstop-1020.js",
    "visual:1019": "./node_modules/.bin/backstop test --docker --config=backstop_data/backstop-1019.js",
    "visual:720": "./node_modules/.bin/backstop test --docker --config=backstop_data/backstop-720.js",
    "visual:719": "./node_modules/.bin/backstop test --docker --config=backstop_data/backstop-719.js",
    "visual:480": "./node_modules/.bin/backstop test --docker --config=backstop_data/backstop-480.js",
    "visual:479": "./node_modules/.bin/backstop test --docker --config=backstop_data/backstop-479.js",
    "visual:320": "./node_modules/.bin/backstop test --docker --config=backstop_data/backstop-320.js",
    "visual": "npm-run-all -c visual:1920 visual:1400 visual:1020 visual:1019 visual:720 visual:719 visual:480 visual:479 visual:320",
```

Individually, the 320 works but NONE of the others do. There are no differences in their backstop-xxxx.js file. 

Any ideas?

**Comment by KITSDominicWhite** [comment]
Successful generate of report (I upgraded to 4.0.3)

```
COMMAND | Executing core for "report"
      compare | OK: TileCarousel backstop_320_TileCarousel_0_app_0_320.png
      compare | OK: Button backstop_320_Button_0_app_0_320.png
      compare | OK: Hyperlink backstop_320_Hyperlink_0_app_0_320.png
      compare | OK: Span backstop_320_Span_0_app_0_320.png
      compare | OK: FloatMedia backstop_320_FloatMedia_0_app_0_320.png
      compare | OK: MessageBox backstop_320_MessageBox_0_app_0_320.png
      compare | OK: HtmlBlock backstop_320_HtmlBlock_0_app_0_320.png
      compare | OK: Title backstop_320_Title_0_app_0_320.png
      compare | OK: Paragraph backstop_320_Paragraph_0_app_0_320.png
      compare | OK: SeoBlock backstop_320_SeoBlock_0_app_0_320.png
      compare | OK: Image backstop_320_Image_0_app_0_320.png
      compare | OK: CategoryTile backstop_320_CategoryTile_0_app_0_320.png
      compare | OK: CollapsibleText backstop_320_CollapsibleText_0_app_0_320.png
      compare | OK: BrandTile backstop_320_BrandTile_0_app_0_320.png
      compare | OK: CategoryDeal backstop_320_CategoryDeal_0_app_0_320.png
      compare | OK: BreadCrumbs backstop_320_BreadCrumbs_0_app_0_320.png
      compare | OK: Accordion backstop_320_Accordion_0_app_0_320.png
      compare | OK: ImageAndTextBanner backstop_320_ImageAndTextBanner_0_app_0_320.png
      compare | OK: Navigation backstop_320_Navigation_0_app_0_320.png
      compare | OK: HrTag backstop_320_HrTag_0_app_0_320.png
      compare | OK: BannerCarousel backstop_320_BannerCarousel_0_app_0_320.png
      compare | OK: UspTile backstop_320_UspTile_0_app_0_320.png
      compare | OK: HeroBanner backstop_320_HeroBanner_0_app_0_320.png
      compare | OK: PopularSearchBanner backstop_320_PopularSearchBanner_0_app_0_320.png
      compare | OK: EditorialTile backstop_320_EditorialTile_0_app_0_320.png
      compare | OK: TabbedContent backstop_320_TabbedContent_0_app_0_320.png
      compare | OK: PricingBanner backstop_320_PricingBanner_0_app_0_320.png
      compare | OK: GalleryCarousel backstop_320_GalleryCarousel_0_app_0_320.png
      compare | OK: Pagination backstop_320_Pagination_0_app_0_320.png
      compare | OK: MasonryTile backstop_320_MasonryTile_0_app_0_320.png
      compare | OK: Roundel backstop_320_Roundel_0_img_0_320.png
      compare | OK: LinkList backstop_320_LinkList_0_app_0_320.png
      compare | OK: Price backstop_320_Price_0_app_0_320.png
      compare | OK: ContentTopic backstop_320_ContentTopic_0_app_0_320.png
      compare | OK: SwatchCard backstop_320_SwatchCard_0_app_0_320.png
      compare | OK: Video backstop_320_Video_0_app_0_320.png
      compare | OK: Ratings backstop_320_Ratings_0_app_0_320.png
      compare | OK: UspBar backstop_320_UspBar_0_app_0_320.png
      compare | OK: VideoBlock backstop_320_VideoBlock_0_app_0_320.png
      compare | OK: ProductTile backstop_320_ProductTile_0_app_0_320.png
      compare | OK: ContentArticles backstop_320_ContentArticles_0_app_0_320.png
      compare | OK: Grid backstop_320_Grid_0_app_0_320.png
      compare | OK: PageLayout backstop_320_PageLayout_0_app_0_320.png
      compare | OK: SlotLayer backstop_320_SlotLayer_0_app_0_320.png
       report | Test completed...
       report | 44 Passed
       report | 0 Failed
       report | Writing browser report
       report | Resources copied
       report | Copied configuration to: /src/backstop_data/html_report_320/config.js
      COMMAND | Executing core for "openReport"
   openReport | Attempting to ping
   openReport | Remote not found. Opening backstop_data/html_report_320/index.html
      COMMAND | Command "report" successfully executed in [4.861s]
      COMMAND | Command "test" successfully executed in [37.658s]
COMMAND | Executing core for "openReport"
openReport | Attempting to ping
   COMMAND | Command "test" successfully executed in [391.431s]
openReport | Remote not found. Opening backstop_data/html_report_320/index.html
```

Unsuccessful generation of the report

```
COMMAND | Executing core for "report"
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: There are some read requests waitng on finished stream
    at module.exports.ChunkStream._end (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:100:7)
    at module.exports.ChunkStream.end (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:86:10)
    at exports.PNG.PNG.end (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/png.js:97:16)
    at ReadStream.onend (_stream_readable.js:651:10)
    at Object.onceWrapper (events.js:277:13)
    at ReadStream.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at exports.PNG.onerror (_stream_readable.js:713:12)
    at exports.PNG.emit (events.js:189:13)
    at module.exports.emit (events.js:189:13)
    at module.exports.ChunkStream._end (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:99:10)
    at module.exports.ChunkStream.end (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:86:10)
    [... lines matching original stack trace ...]
    at endReadableNT (_stream_readable.js:1125:12)
      compare | OK: TileCarousel backstop_480_TileCarousel_0_app_0_480.png
      compare | OK: Button backstop_480_Button_0_app_0_480.png
      compare | OK: Hyperlink backstop_480_Hyperlink_0_app_0_480.png
      compare | OK: Span backstop_480_Span_0_app_0_480.png
      compare | OK: FloatMedia backstop_480_FloatMedia_0_app_0_480.png
      compare | OK: MessageBox backstop_480_MessageBox_0_app_0_480.png
      compare | OK: HtmlBlock backstop_480_HtmlBlock_0_app_0_480.png
      compare | OK: Title backstop_480_Title_0_app_0_480.png
      compare | OK: Paragraph backstop_480_Paragraph_0_app_0_480.png
      compare | OK: CollapsibleText backstop_480_CollapsibleText_0_app_0_480.png
      compare | OK: SeoBlock backstop_480_SeoBlock_0_app_0_480.png
      compare | OK: Accordion backstop_480_Accordion_0_app_0_480.png
      compare | OK: Image backstop_480_Image_0_app_0_480.png
      compare | OK: CategoryDeal backstop_480_CategoryDeal_0_app_0_480.png
      compare | OK: CategoryTile backstop_480_CategoryTile_0_app_0_480.png
      compare | OK: Navigation backstop_480_Navigation_0_app_0_480.png
      compare | OK: ImageAndTextBanner backstop_480_ImageAndTextBanner_0_app_0_480.png
      compare | OK: BrandTile backstop_480_BrandTile_0_app_0_480.png
      compare | OK: HeroBanner backstop_480_HeroBanner_0_app_0_480.png
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: There are some read requests waitng on finished stream
    at module.exports.ChunkStream._end (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:100:7)
    at module.exports.ChunkStream.end (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:86:10)
    at exports.PNG.PNG.end (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/png.js:97:16)
    at ReadStream.onend (_stream_readable.js:651:10)
    at Object.onceWrapper (events.js:277:13)
    at ReadStream.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at exports.PNG.onerror (_stream_readable.js:713:12)
    at exports.PNG.emit (events.js:189:13)
    at module.exports.emit (events.js:189:13)
    at module.exports.ChunkStream._end (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:99:10)
    at module.exports.ChunkStream.end (/usr/local/lib/node_modules/backstopjs/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:86:10)
    [... lines matching original stack trace ...]
    at endReadableNT (_stream_readable.js:1125:12)
      compare | OK: PopularSearchBanner backstop_480_PopularSearchBanner_0_app_0_480.png
      compare | OK: BreadCrumbs backstop_480_BreadCrumbs_0_app_0_480.png
      compare | OK: MasonryTile backstop_480_MasonryTile_0_app_0_480.png
      compare | OK: HrTag backstop_480_HrTag_0_app_0_480.png
      compare | OK: LinkList backstop_480_LinkList_0_app_0_480.png
      compare | OK: Pagination backstop_480_Pagination_0_app_0_480.png
      compare | OK: TabbedContent backstop_480_TabbedContent_0_app_0_480.png
      compare | OK: UspTile backstop_480_UspTile_0_app_0_480.png
      compare | OK: BannerCarousel backstop_480_BannerCarousel_0_app_0_480.png
      compare | OK: Price backstop_480_Price_0_app_0_480.png
      compare | OK: Roundel backstop_480_Roundel_0_img_0_480.png
      compare | OK: ContentTopic backstop_480_ContentTopic_0_app_0_480.png
      compare | OK: PricingBanner backstop_480_PricingBanner_0_app_0_480.png
      compare | OK: EditorialTile backstop_480_EditorialTile_0_app_0_480.png
      compare | OK: SwatchCard backstop_480_SwatchCard_0_app_0_480.png
      compare | OK: Ratings backstop_480_Ratings_0_app_0_480.png
      compare | OK: UspBar backstop_480_UspBar_0_app_0_480.png
      compare | OK: VideoBlock backstop_480_VideoBlock_0_app_0_480.png
      compare | OK: ProductTile backstop_480_ProductTile_0_app_0_480.png
      compare | OK: ContentArticles backstop_480_ContentArticles_0_app_0_480.png
      compare | OK: Grid backstop_480_Grid_0_app_0_480.png
      compare | OK: PageLayout backstop_480_PageLayout_0_app_0_480.png
      compare | OK: SlotLayer backstop_480_SlotLayer_0_app_0_480.png
COMMAND | Executing core for "openReport"
openReport | Attempting to ping
   COMMAND | Command "test" successfully executed in [45.377s]
openReport | Remote not found. Opening backstop_data/html_report_480/index.html
```

**Comment by chrisnoden** [comment]
I am having a similar problem. I am unable to get the report for a full run - if I run an individual scenario, I get the report. If I run everything `backstop test --docker` then I get the previous successful report.

Are you now using delegated mount for docker? There seems to be some randomly HUGE latency issues with that approach on Macs.

**Comment by KITSDominicWhite** [comment]
We figured out that there was an issue with the names. Apparently, there is some miss handling if the names of the tests are just numbers. JavaScript must be interpreting these as numbers. 

Renaming our test scenarios fixed this

**Comment by KonstanciaM** [comment]
im seeing the same issue, it was generating report successfully. I created a new directory and executed the tests, it worked few times, now the error reoccurred. I need to give a demo to my team, do you have any advice how to permanently fix it? thank you

**Comment by garris** [comment]
Try cleaning up your existing directory.  remove all files and directories from your reference and test directories.   Creating dynamic directories can confuse backstop in _some_ cases.

**Comment by KonstanciaM** [comment]
@garris that worked, thank you
