### ISSUE TITLE
Syntax error when backstop init

### ISSUE THREAD

**Issue by orandzheviyman** [garris/BackstopJS#1038]
Hello.

I was install backstopjs locally:
`npm install backstopjs`
but when I try to init:
`$ backstop init
-bash: backstop: command not found`
Or try it directly to bin:
`$ ./node_modules/backstopjs/cli/index.js init`
and get an error:
```
/node_modules/backstopjs/core/util/runPuppet.js:39
async function processScenarioView (scenario, variantOrScenarioLabelSafe, scenarioLabelSafe, viewport, config) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/backstopjs/core/util/createBitmaps.js:10:17)
```

What I doing wrong and how it fix, pls?)

p.s. Version of node is v6.16.0

**Comment by orandzheviyman** [comment]
needed node 7.6+ ;c
