### ISSUE TITLE
moving from an older config to latest

### ISSUE THREAD

**Issue by sturobson** [garris/BackstopJS#1040]
I've just tried to re-implement some tasks that I knew were working but realised, I think, that the config files have changed to the latest version.

This is my current `backstopConfig.js`:

```
var glob = require("glob")

var viewports = [
  {
    "name": "small",
    "width": 375,
    "height": 667
  },

  {
    "name": "medium",
    "width": 768,
    "height": 1024
  },

  {
    "name": "huge",
    "width": 1366,
    "height": 768
  }
];

// Hide any selectors you don't need
var hideSelectors = [];
// Take out any selectors
var removeSelectors = [];
// Just get look at these selectors
var selectors = [];
var scenariosArray = [];
var htmlFiles = glob.sync("live/components/preview/**/*.html");

// Loop through all *.html pages and push to scenariosArray
htmlFiles.forEach(function(file, i) {
  var filename = file;
  scenariosArray.push({
    "label": filename,
    "url": "http://localhost:8888/"+filename,
    "hideSelectors": hideSelectors,
    "removeSelectors": removeSelectors,
    "selectors": selectors,
    "delay": 500
  });
});

module.exports = {
  "id": "SCL Test",
  "viewports": viewports,
  "scenarios": scenariosArray,
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "casper_scripts": "backstop_data/casper_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "casperFlags": [],
  "engine": "phantomjs",
  "report": ["browser"],
  "debug": false
}
```

Where should I be looking to change this to work?

Essentially I want backstop to go through the 'live components' locally and take snapshots to reference, like I said - this worked for an older version - but time moves forward.

Any help / pointers would be great :))

**Comment by sturobson** [comment]
I have `3.8.8` installed - and the version that this worked on was `3.8.5`

I will revert to `3.8.5` to see if it still works. It's been a while

**Comment by sturobson** [comment]
the error message I get when running the initial `reference` is:

```
Loading config:  /Users/admin/Sites/EMBL/vf-core/backstopConfig.js

COMMAND | Executing core for "reference"
  clean | backstop_data/bitmaps_reference was cleaned.
createBitmaps | Selected 0 of 0 scenarios.

Running CasperJS with:  [ '/Users/admin/Sites/EMBL/vf-core/node_modules/backstopjs/capture/genBitmaps.js',
  '--captureConfigFileName=/var/folders/4d/wj37zzfs2b1_c2p_qnnz9bwh0000gn/T/capture/7827efdf3e402d1888c62b966544a1ef064134d7.json' ]
CasperJS:  CREATING NEW REFERENCE FILES
CasperJS:  CasperError: No steps defined, aborting
CasperJS:   /Users/admin/Sites/EMBL/vf-core/phantomjs:/platform/casper.js:1633 in run
^X^X
Testing script failed with code: 1

An unexpected error occurred. You may want to try setting the debug option to `true` in your config file.
      COMMAND | Command "reference" ended with an error after [5.383s]
      COMMAND | Error: An unexpected error occurred. You may want to try setting the debug option to `true` in your config file.
                    at ChildProcess.<anonymous> (/Users/admin/Sites/EMBL/vf-core/node_modules/backstopjs/core/util/createBitmaps.js:224:18)
                    at ChildProcess.emit (events.js:189:13)
                    at ChildProcess.EventEmitter.emit (domain.js:459:23)
                    at maybeClose (internal/child_process.js:970:16)
                    at Socket.stream.socket.on (internal/child_process.js:389:11)
                    at Socket.emit (events.js:189:13)
                    at Socket.EventEmitter.emit (domain.js:459:23)
                    at Pipe._handle.close (net.js:597:12)
[11:36:56] 'backstop_reference' errored after 5.39 s
[11:36:56] Error: An unexpected error occurred. You may want to try setting the debug option to `true` in your config file.
    at ChildProcess.<anonymous> (/Users/admin/Sites/EMBL/vf-core/node_modules/backstopjs/core/util/createBitmaps.js:224:18)
    at ChildProcess.emit (events.js:189:13)
    at ChildProcess.EventEmitter.emit (domain.js:459:23)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:459:23)
    at Pipe._handle.close (net.js:597:12)
```

**Comment by sturobson** [comment]
actually - I think, for the most part, I'm an idiot in not adding all the relevant tasks before testing. I'll close this - as it's not _exactly_ the issue I had. 

I needed to install more things from npm and get my tasks set-up properly. I'm just working on doing that now - so will re-open with better details if I still cannot get it to work

✌️
