### ISSUE TITLE
Error after reference command

### ISSUE THREAD

**Issue by jlly-crs** [garris/BackstopJS#1050]
We've been using BackstopJS as part of a VR/CI project we run in CircleCI, and it had been working like a dream until sometime between 1-2 weeks ago, we started getting this:

```
COMMAND | Executing core for "reference"
  clean | backstop_data/bitmaps_reference was cleaned.
createBitmaps | Selected 2 of 2 scenarios.
      COMMAND | Command "reference" ended with an error after [0.005s]
      COMMAND | TypeError: Cannot read property 'startsWith' of undefined
                    at delegateScenarios (/usr/lib/node_modules/backstopjs/core/util/createBitmaps.js:132:28)
                    at module.exports (/usr/lib/node_modules/backstopjs/core/util/createBitmaps.js:182:19)
                    at /usr/lib/node_modules/backstopjs/core/command/reference.js:22:16
                    at <anonymous>
/usr/lib/node_modules/backstopjs/core/util/createBitmaps.js:132
  } else if (config.engine.startsWith('puppet')) {
                           ^

TypeError: Cannot read property 'startsWith' of undefined
    at delegateScenarios (/usr/lib/node_modules/backstopjs/core/util/createBitmaps.js:132:28)
    at module.exports (/usr/lib/node_modules/backstopjs/core/util/createBitmaps.js:182:19)
    at Object.execute (/usr/lib/node_modules/backstopjs/core/command/test.js:17:14)
    at Object.execute [as test] (/usr/lib/node_modules/backstopjs/core/command/index.js:54:49)
    at execute (/usr/lib/node_modules/backstopjs/core/command/index.js:104:31)
    at module.exports (/usr/lib/node_modules/backstopjs/core/runner.js:6:10)
    at Object.<anonymous> (/usr/lib/node_modules/backstopjs/cli/index.js:39:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
BackstopJS v4.0.6
Loading config:  /root/wp-updates/backstop.json 

COMMAND | Executing core for "test"
createBitmaps | Selected 2 of 2 scenarios.
true
```

It seems like something changed in a recent release that requires us to update how we're passing the values over, but I haven't been able to slueth what so far, [this is one of our backstop.json files](https://github.com/jlly-crs/ci-ricebowl/blob/CCGP/backstop.json). Any help would be appreciated so we can keep using this great tool.

**Comment by jmickela** [comment]
It looks like the backstop.json file now has required options that don't throw errors if they aren't included.

I ran into this same issue and adding  id, engine, engineOptions, and debugWindow settings fixed it.

**Comment by jlly-crs** [comment]
Thanks for the above, it helped, though the other chunk was apparently a set of missing libraries for puppeteer, which I thought we'd already been using so not sure what happened there, but resolved by following the advice in this thread: https://github.com/Googlechrome/puppeteer/issues/290
