### ISSUE TITLE
nodejs integration error

### ISSUE THREAD

**Issue by jennasaurusrex** [garris/BackstopJS#1057]
I found the nodejs integration example page, cloned it down and followed the instructions to generate references. I'm getting thrown an error which I'll paste below: 

```
Config detected:
COMMAND | Executing core for `reference`
  clean | backstop_data/second-project/bitmaps_reference was cleaned.
createBitmaps | Selcted 2 of 2 scenarios.
      COMMAND | Command `reference` ended with an error
      COMMAND | TypeError: Converting circular structure to JSON
                    at JSON.stringify (<anonymous>)
                    at writeReferenceCreateConfig (/Users/jennynorthcott/developer_projects/BackstopJS/examples/nodeIntegration/node_modules/backstopjs/core/util/createBitmaps.js:65:58)
                    at module.exports (/Users/jennynorthcott/developer_projects/BackstopJS/examples/nodeIntegration/node_modules/backstopjs/core/util/createBitmaps.js:139:10)
                    at /Users/jennynorthcott/developer_projects/BackstopJS/examples/nodeIntegration/node_modules/backstopjs/core/command/reference.js:19:14
(node:13681) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at writeReferenceCreateConfig (/Users/jennynorthcott/developer_projects/BackstopJS/examples/nodeIntegration/node_modules/backstopjs/core/util/createBitmaps.js:65:58)
    at module.exports (/Users/jennynorthcott/developer_projects/BackstopJS/examples/nodeIntegration/node_modules/backstopjs/core/util/createBitmaps.js:139:10)
    at /Users/jennynorthcott/developer_projects/BackstopJS/examples/nodeIntegration/node_modules/backstopjs/core/command/reference.js:19:14
(node:13681) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13681) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm wondering if there's a quick fix?

**Comment by garris** [comment]
Hi, the examples are really old.  Try checking the tests directory-- I think there is a working example in there.

**Comment by g000m** [comment]
@jennasaurusrex there's a fix here https://github.com/g000m/BackstopJS/tree/update-nodeIntegration
