### ISSUE TITLE
The "path" argument received type undefined.

### ISSUE THREAD

**Issue by al77ex1** [garris/BackstopJS#1059]
I get an error when testing the page:

```
$ backstop test --filter 'About Us'
error_level was set to 0.                                                                                                                                    [success]
BackstopJS v4.1.4
Loading config:  /src/backstop-settings.js 

COMMAND | Executing core for "test"
createBitmaps | Selected 1 of 23 scenarios.
searching for 6 available ports.
These ports will be used: [9222,9223,9224,9225,9226,9227]
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=320,480"],"port":9222,"waitTimeout":30000,"visible":false,"gotoTimeout":120000,"args":["--no-sandbox"]}
Cookie state restored with: []
SCENARIO > Company » About Us
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=576,768"],"port":9223,"waitTimeout":30000,"visible":false,"gotoTimeout":120000,"args":["--no-sandbox"]}
Cookie state restored with: []
SCENARIO > Company » About Us
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=768,992"],"port":9224,"waitTimeout":30000,"visible":false,"gotoTimeout":120000,"args":["--no-sandbox"]}
Cookie state restored with: []
SCENARIO > Company » About Us
9222 Chrome v75 detected.
9223 Chrome v75 detected.
9224 Chrome v75 detected.
9222 INFO >  BackstopTools have been installed.
9224 INFO >  BackstopTools have been installed.
9223 INFO >  BackstopTools have been installed.

ChromyJS returned an unexpected error while attempting to capture a selector. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.dirname (path.js:1260:5)
    at ensureDirectoryPath (/usr/local/lib/node_modules/backstopjs/core/util/ensureDirectoryPath.js:5:22)
    at module.exports (/usr/local/lib/node_modules/backstopjs/core/util/ensureDirectoryPath.js:14:10)
    at Chromy.saveSelector (/usr/local/lib/node_modules/backstopjs/core/util/runChromy.js:495:9)
    at Chromy._screenshotMultipleSelectors$ (/usr/local/lib/node_modules/backstopjs/node_modules/chromy/dist/index.js:1431:59)
    at tryCatch (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
```

```
docker@cli:/var/www$ node -v
v6.11.3
docker@cli:/var/www$ uname -a
Linux cli 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 GNU/Linux
```

I tried to specify the selector in the scenario:
```
{
  "label": "Company » About Us",
  "url": settings.host + "/about-us",
  "selectors": [
      "body"
  ],
  "misMatchThreshold" : 1
},
```
but this does not lead to a result.

If I turn on the option `"debug": true` - I see the HTML code in the console of this page.

**Comment by garris** [comment]
Can you try using the puppeteer engine instead?

Also -- please try bumping your node to something more recent.

Check the docs for the sanity test.

**Comment by al77ex1** [comment]
@garris 
> Can you try using the puppeteer engine instead?

I tried to replace the rendering engine on "puppeteer". No problem with this engine.
The problem is only with the engine "chromy"

**Comment by lsuchanek** [comment]
> Can you try using the puppeteer engine instead?
> 
> Also -- please try bumping your node to something more recent.
> 
> Check the docs for the sanity test.

Hi. I have same issue and I think I found the problem. This change https://github.com/garris/BackstopJS/commit/b5f9c9691cf4b295fd2c2514488482b082c450a4#diff-e3204928aaa5920f0162f7c1d91a486fL356 cause that `testFilePath` is always `undefined`. After revert this change everything works fine. But I am not sure how to fix this.

**Comment by kevinmpowell** [comment]
I suggest reopening this issue.

@garris I can confirm @lsuchanek's debugging. Running tests with the chrome engine _is_ broken on version 4.1.9. 

Switching to the puppeteer engine is not a quick fix for me. I'm running my tests in docker and changing the engine to puppeteer causes a different failure.

I reverted back to version: 4.0.3 and everything is working as it did before.
