### ISSUE TITLE
With puppeteer, "Failed to launch chrome" error

### ISSUE THREAD

**Issue by kmjch** [garris/BackstopJS#1084]
Hi, some of the scenarios seem to be running, but after a while, this error appears:
```
      COMMAND | Command "test" ended with an error after [34.859s]
      COMMAND | Error: Failed to launch chrome!
                [0819/161753.662:FATAL:feature_list.cc(237)] Check failed: !g_initialized_from_acce
ssor.
                Backtrace:
                        ovly_debug_event [0x00007FFD660AD512+15381554]
                        ovly_debug_event [0x00007FFD660ACAF2+15378962]
                        ovly_debug_event [0x00007FFD660C0413+15459123]
                        ovly_debug_event [0x00007FFD660AF55E+15389822]
                        ovly_debug_event [0x00007FFD6594FF71+7659153]
                        ovly_debug_event [0x00007FFD6602AB21+14846529]
                        ovly_debug_event [0x00007FFD6602AA8A+14846378]
                        ovly_debug_event [0x00007FFD66055958+15022200]
                        ovly_debug_event [0x00007FFD6602A332+14844498]
                        ovly_debug_event [0x00007FFD66054DE6+15019270]
                        ovly_debug_event [0x00007FFD66054CBE+15018974]
                        ovly_debug_event [0x00007FFD66054AF4+15018516]
                        ChromeMain [0x00007FFD652011B6+286]
                        Ordinal0 [0x00007FF6DCE72767+10087]
                        Ordinal0 [0x00007FF6DCE7182B+6187]
                        GetHandleVerifier [0x00007FF6DCF74AD2+663890]
                        BaseThreadInitThunk [0x00007FFDD74C7BD4+20]
                        RtlUserThreadStart [0x00007FFDD79CCE71+33]



                TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/trouble
shooting.md

                    at onClose (C:\workspace\uibackstopautomationtests\node_modules\puppeteer\lib\L
auncher.js:340:14)
                    at ChildProcess.helper.addEventListener (C:\workspace\uibackstopautomationtests
\node_modules\puppeteer\lib\Launcher.js:330:60)
                    at emitTwo (events.js:131:20)
                    at ChildProcess.emit (events.js:214:7)
                    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
Error: Failed to launch chrome!
[0819/161753.662:FATAL:feature_list.cc(237)] Check failed: !g_initialized_from_accessor.
Backtrace:
        ovly_debug_event [0x00007FFD660AD512+15381554]
        ovly_debug_event [0x00007FFD660ACAF2+15378962]
        ovly_debug_event [0x00007FFD660C0413+15459123]
        ovly_debug_event [0x00007FFD660AF55E+15389822]
        ovly_debug_event [0x00007FFD6594FF71+7659153]
        ovly_debug_event [0x00007FFD6602AB21+14846529]
        ovly_debug_event [0x00007FFD6602AA8A+14846378]
        ovly_debug_event [0x00007FFD66055958+15022200]
        ovly_debug_event [0x00007FFD6602A332+14844498]
        ovly_debug_event [0x00007FFD66054DE6+15019270]
        ovly_debug_event [0x00007FFD66054CBE+15018974]
        ovly_debug_event [0x00007FFD66054AF4+15018516]
        ChromeMain [0x00007FFD652011B6+286]
        Ordinal0 [0x00007FF6DCE72767+10087]
        Ordinal0 [0x00007FF6DCE7182B+6187]
        GetHandleVerifier [0x00007FF6DCF74AD2+663890]
        BaseThreadInitThunk [0x00007FFDD74C7BD4+20]
        RtlUserThreadStart [0x00007FFDD79CCE71+33]



TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (C:\workspace\uibackstopautomationtests\node_modules\puppeteer\lib\Launcher.js:340:1
4)
    at ChildProcess.helper.addEventListener (C:\workspace\uibackstopautomationtests\node_modules\pu
ppeteer\lib\Launcher.js:330:60)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

```
My package.json already has `"engineOptions": { "args": ["--no-sandbox"]}`, and I tried to see if there was a way I could plug in something that does the equivalent of `puppeteer.launch({ignoreDefaultArgs: ['--disable-extensions']}` according to https://github.com/GoogleChrome/puppeteer/issues/3681 to package.json but I'm not sure how.  Somehow, can I put it into engineOptions?
I also took a look at https://github.com/garris/BackstopJS/issues/827 and https://github.com/garris/BackstopJS/issues/803, and neither of these seem to apply.  These tests were running fine a few weeks before,

**Comment by kdavisglobal** [comment]
We saw the same, the error is coming from within the Chromium headless browser.  There is this code:

// static
bool FeatureList::InitializeInstance(
    const std::string& enable_features,
    const std::string& disable_features,
    const std::vector<FeatureOverrideInfo>& extra_overrides) {
  // We want to initialize a new instance here to support command-line features
  // in testing better. For example, we initialize a dummy instance in
  // base/test/test_suite.cc, and override it in content/browser/
  // browser_main_loop.cc.
  // On the other hand, we want to avoid re-initialization from command line.
  // For example, we initialize an instance in chrome/browser/
  // chrome_browser_main.cc and do not override it in content/browser/
  // browser_main_loop.cc.
  // If the singleton was previously initialized from within an accessor, we
  // want to prevent callers from reinitializing the singleton and masking the
  // accessor call(s) which likely returned incorrect information.
  CHECK(!g_initialized_from_accessor);

So it basically checks that you don't call Initialize concurrently.  In Puppeteer (Sharp in my case) it calls LaunchAsync which means this could intermittently happen.  Ideally they should have a mutex or critical section so multiple threads cannot initialize at the same time, but failing that, you can add this to your calling code to synchronize access and avoid the error.  That's what we did!

**Comment by VinS101** [comment]
We are experiencing the same error! Our tests were running fine until some of them started randomly failing due to this exact error!

**Comment by romanzenka** [comment]
We are running into this problem intermittently, and it is making our tests very flaky!
What can we do to resolve this issue? 
Disabling all parallelism sounds like an expensive solution that would slow our builds down dramatically. We are running 5 instances concurrently.

**Comment by garris** [comment]
Sorry, I have not experienced this -- but I am on Mac and Linux exclusively.

**Comment by romanzenka** [comment]
Our build system is on TFS, Windows only, so we are forced to run Backstop on Windows, because font rendering is inconsistent between platforms.

Sadly, Docker is not supported on our TFS instance, so we are SOL.

For now we disabled the parallelism and the errors ceased. The builds take much longer.

I am realizing that while we experienced this through Backstop, the issue should really get fixed in Puppeteer, would you agree, @kdavisglobal  ?

**Comment by kdavisglobal** [comment]
Yes @romanzenka it's really an issue with Puppeteer, but you could workaround it the same way we did.  

We had something like the following:

private static readonly object _initializeLock = new object();

Browser browser = null;

lock (_initializeLock)
{
      var task = Puppeteer.LaunchAsync(options);
      task.Wait();
      browser = task.Result;
}

**Comment by madelson** [comment]
@kdavisglobal are you using puppeteer sharp? Is there an issue in their repository for this error?

**Comment by fqrd** [comment]
Any solution for this problem ? I'm experiencing it aswell with nodeJS on a windows server 2016.

**Comment by garris** [comment]
Does this fix itself if you just set executablePath to a local prod download of chrome?

**Comment by madelson** [comment]
@garris I believe we are using a prod download of Chrome (as opposed to Chromium) in the environment where we occasionally see this. 

Do you know if synchronizing browser launches as suggested by @kdavisglobal is a real fix?

**Comment by kdavisglobal** [comment]
Sorry I don't use GitHub very often and get lots of spam for this email. Yes, it's technically something puppeteer sharp should fix as it's happening in Puppeteer.LaunchAsync but it's because it uses the contained chromium engine or headless browser which cannot safely render in a multi threaded set up. I wouldn't advocate disabling parallelism for anything other than a really to confirm as we did. Putting a lock around the async call is sufficient.
