### ISSUE TITLE
Fresh Xubuntu Install | NODEJS 10 | Fails to install on puppeteer

### ISSUE THREAD

**Issue by eanbowman** [garris/BackstopJS#1119]
```
sudo npm install -g backstopjs
npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/bin/backstop -> /usr/lib/node_modules/backstopjs/cli/index.js

> puppeteer@1.20.0 install /usr/lib/node_modules/backstopjs/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/backstopjs/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/lib/node_modules/backstopjs/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/lib/node_modules/backstopjs/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/lib/node_modules/backstopjs/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lilithe/.npm/_logs/2019-11-22T21_03_44_589Z-debug.log
```

**Comment by eanbowman** [comment]
```sudo npm install -g backstopjs
[sudo] password for lilithe: 
npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/bin/backstop -> /usr/lib/node_modules/backstopjs/cli/index.js

> puppeteer@1.20.0 install /usr/lib/node_modules/backstopjs/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/backstopjs/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/lib/node_modules/backstopjs/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/lib/node_modules/backstopjs/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/lib/node_modules/backstopjs/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lilithe/.npm/_logs/2019-11-28T21_36_57_531Z-debug.log
lilithe@CQ-CE-24727:/mnt/data/Source/bbcan8-wp$ 
```
Still have this issue.

**Comment by alastairmoore** [comment]
Also experiencing the same issue. There is a workaround:

sudo npm install -g backstopjs --unsafe-perm=true --allow-root

But not especially happy doing this.

**Comment by lilithebowman** [comment]
The fix doesn't work anymore.

```
$ sudo npm install -g backstopjs --unsafe-perm=true --allow-root
[sudo] password for liltester: 
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/backstop -> /usr/local/lib/node_modules/backstopjs/cli/index.js
+ backstopjs@5.0.6
updated 1 package in 6.541s

$ backstop test
BackstopJS v5.0.6
Loading config:  /home/liltester/source/wp-audit-dashboard/backstopjs/backstop.json 

COMMAND | Executing core for "test"
createBitmaps | Selected 1 of 1 scenarios.
      COMMAND | Command "test" ended with an error after [0.006s]
      COMMAND | Error: Browser is not downloaded. Run "npm install" or "yarn install"
                    at ChromeLauncher.launch (/usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/lib/Launcher.js:236:15)
```

**Comment by garris** [comment]
Does bumping puppeteer to a more recent version resolve this for you?  Did you try that?

**Comment by fuhlig** [comment]
> Does bumping puppeteer to a more recent version resolve this for you? Did you try that?

How safe is it to update puppeteer (to the current version)? 
As backstop is fixed @ puppeteer v2

**Comment by lilithebowman** [comment]
I basically ended up coding my own visual diff tool using Github Actions, shell scripts, and puppeteer JS. 🤷‍♀️

**Comment by lilithebowman** [comment]
```
liltester@pop-os:/tmp/backstopjs$ npm install -D puppeteer --unsafe-perms

> puppeteer@2.1.1 install /tmp/backstopjs/node_modules/backstopjs/node_modules/puppeteer
> node install.js

Downloading Chromium r722234 - 121.1 Mb [====================] 100% 0.0s 
Chromium downloaded to /tmp/backstopjs/node_modules/backstopjs/node_modules/puppeteer/.local-chromium/linux-722234

> puppeteer@5.3.1 install /tmp/backstopjs/node_modules/puppeteer
> node install.js

Downloading Chromium r800071 - 128.4 Mb [====================] 100% 0.0s 
Chromium (800071) downloaded to /tmp/backstopjs/node_modules/puppeteer/.local-chromium/linux-800071
npm WARN backstopjs No description
npm WARN backstopjs No repository field.
npm WARN backstopjs No license field.

+ puppeteer@5.3.1
added 38 packages from 64 contributors, updated 5 packages, moved 1 package and audited 246 packages in 43.171s

8 packages are looking for funding
  run `npm fund` for details

found 1 high severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
liltester@pop-os:/tmp/backstopjs$ backstop test
`resolve/lib/core` is deprecated; please use `is-core-module` directly
BackstopJS v5.0.2
Loading config:  /tmp/backstopjs/backstop.json 

COMMAND | Executing core for "test"
createBitmaps | Selected 1 of 1 scenarios.
      COMMAND | Command "test" ended with an error after [0.005s]
      COMMAND | Error: Browser is not downloaded. Run "npm install" or "yarn install"
                    at ChromeLauncher.launch (/usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/lib/Launcher.js:236:15)
```

**Comment by lilithebowman** [comment]
```
liltester@pop-os:/tmp/backstopjs$ chrome --version
Chromium 83.0.4103.116 built on Debian bullseye/sid, running on Debian bullseye/sid
```
