### ISSUE TITLE
backstop reference fails to launch browser on windows

### ISSUE THREAD

**Issue by diminutivesloop** [garris/BackstopJS#1157]
On my windows 10 machine the `backstop reference` command fails with the following error:
```
COMMAND | Command "reference" ended with an error after [1.604s]
      COMMAND | Error: Failed to launch the browser process!


                TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

                    at onClose (C:\Users\npalmer\AppData\Roaming\nvm\v10.16.3\node_modules\backstopjs\node_modules\puppeteer\lib\Launcher.js:750:14)
                    at ChildProcess.helper.addEventListener (C:\Users\npalmer\AppData\Roaming\nvm\v10.16.3\node_modules\backstopjs\node_modules\puppeteer\lib\Launcher.js:740:61)
                    at ChildProcess.emit (events.js:203:15)
                    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

This happens even with the default config created by `backstop init`. I tried adding `ignoreDefaultArgs: ['--disable-extensions']` and `args: ['--disable-setuid-sandbox']` to `engineOptions` but that didn't change anything.

**Comment by garris** [comment]
Please try this...

https://github.com/garris/BackstopJS#sanity-test-does-backstop-work-in-my-environment

**Comment by diminutivesloop** [comment]
Just ran the command and I got the same error:
```
$ mkdir backstopSanityTest; cd backstopSanityTest; npm install backstopjs; node ./node_modules/backstopjs/cli/ init; node ./node_modules/backstopjs/cli/ test
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> puppeteer@2.1.1 install C:\Users\npalmer\backstopSanityTest\node_modules\puppeteer
> node install.js


Chromium downloaded to C:\Users\npalmer\backstopSanityTest\node_modules\puppeteer\.local-chromium\win64-722234

> core-js@2.6.11 postinstall C:\Users\npalmer\backstopSanityTest\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\npalmer\backstopSanityTest\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\npalmer\backstopSanityTest\package.json'
npm WARN backstopSanityTest No description
npm WARN backstopSanityTest No repository field.
npm WARN backstopSanityTest No README data
npm WARN backstopSanityTest No license field.

+ backstopjs@4.5.0
added 225 packages from 244 contributors in 64.922s

2 packages are looking for funding
  run `npm fund` for details

BackstopJS v4.5.0
COMMAND | Executing core for "init"
   init | Copying 'C:\Users\npalmer\backstopSanityTest\node_modules\backstopjs\capture\engine_scripts' to 'C:\Users\npa
lmer\backstopSanityTest\backstop_data\engine_scripts'
   init | Configuration file written at 'C:\Users\npalmer\backstopSanityTest\backstop.json'
COMMAND | Command "init" successfully executed in [0.122s]
BackstopJS v4.5.0
Loading config:  C:\Users\npalmer\backstopSanityTest\backstop.json

COMMAND | Executing core for "test"
createBitmaps | Selected 1 of 1 scenarios.
      COMMAND | Command "test" ended with an error after [1.241s]
      COMMAND | Error: Failed to launch the browser process!


                TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

                    at onClose (C:\Users\npalmer\backstopSanityTest\node_modules\puppeteer\lib\Launcher.js:750:14)
                    at ChildProcess.helper.addEventListener (C:\Users\npalmer\backstopSanityTest\node_modules\puppeteer
\lib\Launcher.js:740:61)
                    at ChildProcess.emit (events.js:203:15)
                    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
```

**Comment by garris** [comment]
Hmm.   It looks like puppeteer is not able to launch chrome.  In some other directory -- can you try installing and running a vanilla puppeteer script?  Please try this with the same puppeteer version BackstopJS is using.

**Comment by diminutivesloop** [comment]
Ok so I did a little digging and it looks like there's an issue with the versions of Chromium that puppeteer ^2.0.0 depends on. I've opened an [issue](https://github.com/puppeteer/puppeteer/issues/5478) and based on my testing the latest version of Chromium fixes the issue. Is there a workaround I can try in the meantime or is my best bet to use an older version of backstopjs?

**Comment by garris** [comment]
Ok, Then please document the puppeteer link here.  Also, are there newer versions of puppeteer which do not have this issue? 

**Workarounds... Ordered by level of complexity**

Workaround 1)  you can use the docker option (see the docs).  Then you are not sacrificing anything.

Workaround 2) you can manually load a compatible version of chrome and tell backstop to use that instead (check the docs for how to do this -- it's pretty easy.)  

Workaround 3) wipe your laptop and install Ubuntu FTW!! 😛

**Comment by diminutivesloop** [comment]
Ok I did include a link in my last comment. Let me know if there's something else I need to include. And no the issue affects all 2.x.x versions of puppeteer including the latest one.

As for a workaround I think the best solution for me will be to just use backstopjs 4.4.2.
