### ISSUE TITLE
Install BackStopJs

### ISSUE THREAD

**Issue by xbouillet** [garris/BackstopJS#1275]
Hello,

I have a unbuntu 18.04
I try to install BackstopJs.

I make the following command: 

`
apt-get upgrade`
`apt install npm`
`npm install -g backstopjs`
`
After, i go to my project's directory and run:

`backstop init`

It gives me the following error 

```
/usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:707
        catch {
              ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/lib/cjs/puppeteer/common/Target.js:19:19)

```

I've tried everything,  :'( :'( :'( 

Please,  how can I finish my installation :) :)

My version of nodejs is v8.10.0

Thanks

**Comment by xbouillet** [comment]
I have upgrade nodeJs, and it seems ok

curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs

Sorry
