### ISSUE TITLE
I can't run BackstopJS tests on Docker

### ISSUE THREAD

**Issue by Antonytm** [garris/BackstopJS#1289]
Steps to reproduce, I run next commands(tried Windows Command Prompt and Windows Powershell):
1) `npm i backstopjs -g`
2) `backstopjs init`
3) `backstopjs test`
4) `backstopjs approve`
5) `backstop test --docker`

*Expected result:*
The test should be executed in the same way as on step 3
*Actual result:*

```
BackstopJS v5.1.0
Loading config:  C:\Source\backstopJSRunner\backstop.json

COMMAND | Executing core for "test"
Delegating command to Docker... docker run --rm -it --mount type=bind,source="C:\Source\backstopJSRunner",target=/src backstopjs/backstopjs:5.1.0 test "--moby"
docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: '/src'.
See 'docker run --help'.
COMMAND | Executing core for "openReport"
openReport | Attempting to ping
   COMMAND | Command "test" ended with an error after [1.847s]
   COMMAND | Error: docker run --rm -it --mount type=bind,source="C:\Source\backstopJSRunner",target=/src backstopjs/backstopjs:5.1.0 test "--moby" returned 125
                 at ChildProcess.<anonymous> (C:\Users\Anton\AppData\Roaming\nvm\v12.18.3\node_modules\backstopjs\core\util\runDocker.js:68:18)
                 at ChildProcess.emit (events.js:315:20)
                 at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
openReport | Remote not detected. Opening backstop_data\html_report\index.html

C:\Source\backstopJSRunner>docker run --rm -it --mount type=bind,source="C:\Source\backstopJSRunner",target=/src backstopjs/backstopjs:5.1.0 test "--moby"
docker: Error response from daemon: invalid mount config for type "bind": invalid mount path: '/src'.
See 'docker run --help'.
```

![image](https://user-images.githubusercontent.com/647813/111066405-7fa7e500-84c7-11eb-9184-13d911ba34fe.png)

**Comment by garris** [comment]
I believe this was fixed in 5.3.0...
https://github.com/garris/BackstopJS/issues/1291#issuecomment-807972839

**Comment by Antonytm** [comment]
@garris 

I have tried 5.3.0, but the result is the same.
![image](https://user-images.githubusercontent.com/647813/112994720-32886c00-9173-11eb-8011-1b35f427e971.png)
