### ISSUE TITLE
I can`t init backstopjs in latest docker container(5.2.1)

### ISSUE THREAD

**Issue by svicervlad** [garris/BackstopJS#1291]
Steps to reproduce:
- `docker run --rm -v $(pwd):/src backstopjs/backstopjs:5.2.1 init`

Expected result:
The init should be executed without errors
Actual result:
```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/backstopjs/core/util/runPuppet.js:1:81)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```
![image](https://user-images.githubusercontent.com/26228931/112471519-ae9a4280-8d74-11eb-9502-d24a39a882c3.png)

**Comment by digitaldonkey** [comment]
Was about to write that too .....

**Comment by LuluYang-tw** [comment]
ran into same issue too

**Comment by garris** [comment]
🤦‍♂️

**Comment by garris** [comment]
Maybe it's this...

https://github.com/garris/BackstopJS/commit/037922149edc9c30fb2b950d4ba5d937f51a06e7

**Comment by svicervlad** [comment]
Latest container backstopjs/backstopjs:5.3.0 works fine, Thanks @garris

**Comment by garris** [comment]
Thanks for confirming @svicervlad!
