### ISSUE TITLE
getting ignoreHTTPSErrors error when i run backstop init, below is the error log

### ISSUE THREAD

**Issue by bharath4793** [garris/BackstopJS#1380]
backstop init
/Users/<user>/.nvm/versions/node/v12.22.7/lib/node_modules/backstopjs/core/util/runPlaywright.js:75
  const ignoreHTTPSErrors = config.engineOptions.ignoreHTTPSErrors ?? true;
                                                                    ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/<user>/.nvm/versions/node/v12.22.7/lib/node_modules/backstopjs/core/util/createBitmaps.js:7:23)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)    

tried to follow the steps that was specified in https://github.com/puppeteer/puppeteer/issues/3119
didn't know where do I add ignoreHTTPSErrors: true option... 

i have just installed backstop js globally and tried backstop init. and got the above error. 

node version that i am using is v12.22.7

**Comment by bharathb-rfk** [comment]
the above issue was resolved when i upgraded the node version to v17.1.0

**Comment by bharath4793** [comment]
the above issue was resolved when i upgraded the node to v17.1.0

**Comment by bharath4793** [comment]
the above issue was resolved when i upgraded the node to v17.1.0

**Comment by datdoan** [comment]
> the above issue was resolved when i upgraded the node to v17.1.0

Works on 16.13.0 too.
