### ISSUE TITLE
Chromium not available for non root user within docker for Playwright at version 6.2.0

### ISSUE THREAD

**Issue by websi** [garris/BackstopJS#1468]
With Version 6.2.0 the chromium browser is not available for non root user. The normal user is `node`. See https://github.com/garris/BackstopJS/blob/1144782deebfe7e70650f09cc7fa2d3ffb349f7a/docker/Dockerfile#L18

```
$ docker run --rm -v $CI_PROJECT_DIR:/src  backstopjs/backstopjs:6.2.0 test --config=backstop.config.js
BackstopJS v6.2.0
Loading config:  /src/backstop.config.js 
COMMAND | Executing core for "test"
createBitmaps | Selected 10 of 10 scenarios.
Creating Browser
      COMMAND | Command "test" ended with an error after [0.007s]
      COMMAND | browserType.launch: Executable doesn't exist at /home/node/.cache/ms-playwright/chromium-1048/chrome-linux/chrome
                ╔═════════════════════════════════════════════════════════════════════════╗
                ║ Looks like Playwright Test or Playwright was just installed or updated. ║
                ║ Please run the following command to download new browsers:              ║
                ║                                                                         ║
                ║     npx playwright install                                              ║
                ║                                                                         ║
                ║ <3 Playwright Team                                                      ║
                ╚═════════════════════════════════════════════════════════════════════════╝
                    at module.exports.createPlaywrightBrowser (/usr/local/lib/node_modules/backstopjs/core/util/runPlaywright.js:43:42)
                    at /usr/local/lib/node_modules/backstopjs/core/util/createBitmaps.js:136:7
                    at delegateScenarios (/usr/local/lib/node_modules/backstopjs/core/util/createBitmaps.js:1[35](https://gitlab.dkd.de/dkd/products/typo3-cms-standard/-/jobs/242187#L35):12)
                    at module.exports (/usr/local/lib/node_modules/backstopjs/core/util/createBitmaps.js:192:19)
                    at Object.execute (/usr/local/lib/node_modules/backstopjs/core/command/test.js:17:14)
                    at Object.execute [as test] (/usr/local/lib/node_modules/backstopjs/core/command/index.js:59:49)
                    at execute (/usr/local/lib/node_modules/backstopjs/core/command/index.js:109:31)
                    at module.exports (/usr/local/lib/node_modules/backstopjs/core/runner.js:6:10)
                    at main (/usr/local/lib/node_modules/backstopjs/cli/index.js:[40](https://gitlab.dkd.de/dkd/products/typo3-cms-standard/-/jobs/242187#L40):5)
                    at Object.<anonymous> (/usr/local/lib/node_modules/backstopjs/cli/index.js:8:1)
```

Current workaround is to start the image as root user.

```
$ docker run --rm -v $CI_PROJECT_DIR:/src -u root backstopjs/backstopjs:6.2.0 test --config=backstop.config.js
```

**Comment by tsvetislavt99** [comment]
Running into the same issue. 

@tkrah I made a [small repo](https://github.com/tsvetislavt99/backstop-6.2.0-docker-issue) where this can be reproduced.

**Comment by tkrah** [comment]
> Running into the same issue.
> 
> @tkrah I made a [small repo](https://github.com/tsvetislavt99/backstop-6.2.0-docker-issue) where this can be reproduced.

```
      COMMAND | TypeError: Cannot read properties of undefined (reading 'replace')
                    at Object.makeSafe (/usr/local/lib/node_modules/backstopjs/core/util/engineTools.js:48:14)
                    at module.exports.runPlaywright (/usr/local/lib/node_modules/backstopjs/core/util/runPlaywright.js:51:41)
                    at /usr/local/lib/node_modules/backstopjs/node_modules/p-map/index.js:57:28

```

trying to run your backstop example just always ends in that for me, ideas? using npm 9.6.2 with node 18.x.

**Comment by tsvetislavt99** [comment]
> trying to run your backstop example just always ends in that for me, ideas? using npm 9.6.2 with node 18.x.

@tkrah Sorry forgot to make `.nvmrc`. I'm on `node - 16.14.2` `npm - 8.19.4`

**Comment by tkrah** [comment]
@websi @tsvetislavt99  Do you still have that problem with 6.2.2? Should be working again now.

**Comment by tsvetislavt99** [comment]
@tkrah Hey, yes I can confirm the issue is resolved with me.

**Comment by websi** [comment]
I can also confirm that the issue was resolved.
