### ISSUE TITLE
Can't install on debian 11 | Fails to install puppeteer

### ISSUE THREAD

**Issue by vistar** [garris/BackstopJS#1544]
But I want to use playwright.

Local install `npm install backstopjs` and global `npm install -g backstopjs` gets an errors:

`...
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/backstopjs/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c node install.mjs
npm ERR! file:///usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/install.mjs:31
npm ERR!   const {downloadBrowser} = await importInstaller();
npm ERR!                             ^^^^^
npm ERR! 
npm ERR! SyntaxError: Unexpected reserved word
npm ERR!     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
npm ERR!     at async link (internal/modules/esm/module_job.js:42:21)
`

`
npm --version
7.5.2

node --version
v12.22.12

lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
`

**Comment by vistar** [comment]
All is ok after update npm and nodejs:

```
npm --version
10.4.0

node --version
v21.6.2
```
