### ISSUE TITLE
Test errors, but there is no difference in the snapshots when observed with the naked eye

### ISSUE THREAD

**Issue by lpeabody** [garris/BackstopJS#1562]
Hello! Thanks for the awesome tool. 

I am struggling to come up with an explanation for why a test(s) may be flagged as failed by Backstop, but when comparing the snapshot and looking at the diff there is no discernible difference between reference and test images to the naked eye. Due to confidentiality reasons I am unable to post the failing tests/snapshots. Here is some supporting information:

- This happens inconsistently.
- Tests are executed in Docker using `backstopjs/backstopjs:6.3.23` on a GitHub Actions runner machine.
- The suspect results come from the same scenario at 3 of the 7 tested breakpoints.
    - The test is a full-page screenshot, of significant length.
- There is no log output that would indicate an error occurred.
- The failure message in the test result looks like:

```
   See: /src/backstop_data/bitmaps_test/20240405-020130/failed_diff_backstop_default_scrubbed-_Homepage_0_document_0_mobile.png
   See: /src/backstop_data/bitmaps_test/20240405-020130/failed_diff_backstop_default_scrubbed-_Homepage_0_document_2_tablet.png
   See: /src/backstop_data/bitmaps_test/20240405-020130/failed_diff_backstop_default_scrubbed-_Homepage_0_document_1_mobile-lg.png
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 0.00%, threshold: 0.1% }: scrubbed - Homepage backstop_default_scrubbed-_Homepage_0_document_1_mobile-lg.png
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 0.00%, threshold: 0.1% }: scrubbed - Homepage backstop_default_scrubbed-_Homepage_0_document_0_mobile.png
      compare | ERROR { requireSameDimensions: true, size: isDifferent, content: 0.00%, threshold: 0.1% }: scrubbed - Homepage backstop_default_scrubbed-_Homepage_0_document_2_tablet.png
```

This is also at the end of the report:

```
       report | *** Mismatch errors found ***
      COMMAND | Command "report" ended with an error after [3.711s]
      COMMAND | Error: Mismatch errors found.
                    at /usr/local/lib/node_modules/backstopjs/core/command/report.js:284:17
                    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      COMMAND | Command "test" ended with an error after [62.293s]
      COMMAND | Error: Mismatch errors found.
                    at /usr/local/lib/node_modules/backstopjs/core/command/report.js:284:17
                    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Scenario configuration:

```
  "scenarioDefaults": {
    "cookiePath": "backstop_data/engine_scripts/cookies.json",
    "referenceUrl": "",
    "readyEvent": "Ready for BackstopJS tests",
    "readySelector": "",
    "delay": 5000,
    "hideSelectors": [],
    "removeSelectors": [],
    "hoverSelector": "",
    "clickSelector": "",
    "postInteractionWait": 0,
    "selectors": [],
    "selectorExpansion": true,
    "expect": 0,
    "misMatchThreshold" : 0.1,
    "requireSameDimensions": true,
    "scrollToSelector": ".scrubbed",
    "loginAs": "admin",
    "suppressToolbar": true
  },
  "scenarios": [
    {
      "label": "Scrubbed - Homepage",
      "url": "https://drupal-" + VIRTUAL_HOST,
    }
  ],
```

Sorry for not being able to post the images. Given the information provided so far, do you have any thoughts as to what might be the cause?

**Comment by lpeabody** [comment]
Of course after posting this I see `requireSameDimensions: true`, and when looking at one of the failed tests the reference image is 320x13486, while the test image is 320x13528. There is an extra 42 pixels of whitespace padded at the bottom of the test image. I have no idea why this is happening, and I've no idea why this wouldn't fail the content mismatch threhshold constraint?

**Comment by lpeabody** [comment]
Going to close this, `requireSameDimensions: true` seems to have resolved the issue. It's less reliable but I think it's good enough, will just keep an eye on it.
