### ISSUE TITLE
Wrong src link in html report for ressemble images

### ISSUE THREAD

**Issue by stephenbe** [garris/BackstopJS#300]
Hello,

In the report the link to the ressemble is wrong.

![2016-10-04_13-07-18](https://cloud.githubusercontent.com/assets/3018441/19084215/9946651a-8a33-11e6-8541-208f89259c8b.png)

What is in the src : 

```
..\..\C:\Projets\N3\fwd-webapp-overlay-skin\backstop_data\bitmaps_test\light\20161004-130641\failed_diff_01046322484_Tous_les_headings_0_n3-doc-heading_0_phone.png
```

What it should be : 
```
C:\Projets\N3\fwd-webapp-overlay-skin\backstop_data\bitmaps_test\light\20161004-130641\failed_diff_01046322484_Tous_les_headings_0_n3-doc-heading_0_phone.png
```

Seems like it adds "..\ ..\" too many before the C:

Thanks!

**Comment by garris** [comment]
Please provide terminal log including the command you used to launch the process.

**Comment by garris** [comment]
Also,  what version of backstop are you on?  Please make sure you are on 2.0.2.

**Comment by stephenbe** [comment]
I am on the version 2.0.2 on windows 7

Thanks!

```
C:\Projets\N3\fwd-webapp-overlay-skin>backstop test --configPath=backstop_data/backstopTests/backstop-light.js

BackstopJS CWD:  C:\Projets\N3\fwd-webapp-overlay-skin
BackstopJS loading config:  C:\Projets\N3\fwd-webapp-overlay-skin\backstop_data\backstopTests\backstop-light.js

COMMAND | Executing core for `test`

Running CasperJS with:  [ 'C:\\Users\\ddu2949\\AppData\\Roaming\\npm\\node_modules\\backstopjs\\capture\\genBitmaps.js' ]
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html#boutons
CasperJS:  Capturing screenshots for phone (320x480)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html#boutons
CasperJS:  Capturing screenshots for tablet_v (568x1024)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html#boutons
CasperJS:  Capturing screenshots for tablet_h (1024x768)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html#boutons
CasperJS:  Capturing screenshots for phone (320x480)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html#boutons
CasperJS:  Capturing screenshots for tablet_v (568x1024)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html#boutons
CasperJS:  Capturing screenshots for tablet_h (1024x768)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html#boutons
CasperJS:  Capturing screenshots for phone (320x480)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html#boutons
CasperJS:  Capturing screenshots for tablet_v (568x1024)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html#boutons
CasperJS:  Capturing screenshots for tablet_h (1024x768)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?touch=true#boutons
CasperJS:  Capturing screenshots for phone (320x480)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?touch=true#boutons
CasperJS:  Capturing screenshots for tablet_v (568x1024)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?touch=true#boutons
CasperJS:  Capturing screenshots for tablet_h (1024x768)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?touch=true#boutons
CasperJS:  Capturing screenshots for phone (320x480)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?touch=true#boutons
CasperJS:  Capturing screenshots for tablet_v (568x1024)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?touch=true#boutons
CasperJS:  Capturing screenshots for tablet_h (1024x768)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?touch=true#boutons
CasperJS:  Capturing screenshots for phone (320x480)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?touch=true#boutons
CasperJS:  Capturing screenshots for tablet_v (568x1024)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?touch=true#boutons
CasperJS:  Capturing screenshots for tablet_h (1024x768)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html#typographie
CasperJS:  Capturing screenshots for phone (320x480)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html#typographie
CasperJS:  Capturing screenshots for tablet_v (568x1024)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html#typographie
CasperJS:  Capturing screenshots for tablet_h (1024x768)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?touch=true#typographie
CasperJS:  Capturing screenshots for phone (320x480)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?touch=true#typographie
CasperJS:  Capturing screenshots for tablet_v (568x1024)
CasperJS:  Ready event received.
CasperJS:  Current location is http://localhost:4000/documentation/3.3/composantes.html?touch=true#typographie
CasperJS:  Capturing screenshots for tablet_h (1024x768)
CasperJS:  Comparison config file updated.

Bitmap file generation completed.
COMMAND | Executing core for `report`
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_0_n3-doc-btn-abtn-default_0_phone.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_0_n3-doc-btn-abtn-default_1_tablet_v.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_0_n3-doc-btn-abtn-default_2_tablet_h.png
compare | OK: Bouton divisé 01046322484_Bouton_divis_0_dropdown-divise_1_tablet_v.png
compare | OK: Bouton divisé 01046322484_Bouton_divis_0_dropdown-divise_2_tablet_h.png
compare | OK: Bouton divisé 01046322484_Bouton_divis_0_dropdown-divise_0_phone.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_0_n3-doc-btn-abtn-default_0_phone.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_0_n3-doc-btn-abtn-default_1_tablet_v.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_0_n3-doc-btn-abtn-default_2_tablet_h.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_3_n3-doc-btn-abtn-danger_0_phone.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_1_n3-doc-btn-abtn-primary_0_phone.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_2_n3-doc-btn-abtn-primarybtn-block_0_phone.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_5_n3-doc-btn-abtn-primarycadenas_0_phone.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_4_n3-doc-btn-abtn-primarycrochet_0_phone.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_6_n3-doc-btn-abtn-defaultprecedent_0_phone.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_7_n3-doc-btn-abtn-defaultsuivant_0_phone.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_1_n3-doc-btn-abtn-primary_1_tablet_v.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_2_n3-doc-btn-abtn-primarybtn-block_1_tablet_v.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_3_n3-doc-btn-abtn-danger_1_tablet_v.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_4_n3-doc-btn-abtn-primarycrochet_1_tablet_v.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_5_n3-doc-btn-abtn-primarycadenas_1_tablet_v.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_6_n3-doc-btn-abtn-defaultprecedent_1_tablet_v.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_7_n3-doc-btn-abtn-defaultsuivant_1_tablet_v.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_2_n3-doc-btn-abtn-primarybtn-block_2_tablet_h.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_1_n3-doc-btn-abtn-primary_2_tablet_h.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_5_n3-doc-btn-abtn-primarycadenas_2_tablet_h.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_4_n3-doc-btn-abtn-primarycrochet_2_tablet_h.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_6_n3-doc-btn-abtn-defaultprecedent_2_tablet_h.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_7_n3-doc-btn-abtn-defaultsuivant_2_tablet_h.png
compare | OK: Tous les boutons 01046322484_Tous_les_boutons_3_n3-doc-btn-abtn-danger_2_tablet_h.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_1_n3-doc-btn-abtn-primary_0_phone.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_4_n3-doc-btn-abtn-primarycrochet_0_phone.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_5_n3-doc-btn-abtn-primarycadenas_0_phone.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_3_n3-doc-btn-abtn-danger_0_phone.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_6_n3-doc-btn-abtn-defaultprecedent_0_phone.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_7_n3-doc-btn-abtn-defaultsuivant_0_phone.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_1_n3-doc-btn-abtn-primary_1_tablet_v.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_3_n3-doc-btn-abtn-danger_1_tablet_v.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_4_n3-doc-btn-abtn-primarycrochet_1_tablet_v.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_5_n3-doc-btn-abtn-primarycadenas_1_tablet_v.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_7_n3-doc-btn-abtn-defaultsuivant_1_tablet_v.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_6_n3-doc-btn-abtn-defaultprecedent_1_tablet_v.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_1_n3-doc-btn-abtn-primary_2_tablet_h.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_3_n3-doc-btn-abtn-danger_2_tablet_h.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_4_n3-doc-btn-abtn-primarycrochet_2_tablet_h.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_5_n3-doc-btn-abtn-primarycadenas_2_tablet_h.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_6_n3-doc-btn-abtn-defaultprecedent_2_tablet_h.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_7_n3-doc-btn-abtn-defaultsuivant_2_tablet_h.png
compare | OK: Bouton divisé touch 01046322484_Bouton_divis_touch_0_dropdown-divise_0_phone.png
compare | OK: Bouton divisé touch 01046322484_Bouton_divis_touch_0_dropdown-divise_1_tablet_v.png
compare | OK: Bouton divisé touch 01046322484_Bouton_divis_touch_0_dropdown-divise_2_tablet_h.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_2_n3-doc-btn-abtn-primarybtn-block_0_phone.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_2_n3-doc-btn-abtn-primarybtn-block_1_tablet_v.png
compare | OK: Tous les boutons touch 01046322484_Tous_les_boutons_touch_2_n3-doc-btn-abtn-primarybtn-block_2_tablet_h.png
compare | OK: Groupe de boutons 01046322484_Groupe_de_boutons_0_n3-group-vertical_0_phone.png
compare | OK: Groupe de boutons 01046322484_Groupe_de_boutons_0_n3-group-vertical_1_tablet_v.png
compare | OK: Groupe de boutons 01046322484_Groupe_de_boutons_0_n3-group-vertical_2_tablet_h.png
compare | OK: Groupe de boutons touch 01046322484_Groupe_de_boutons_touch_0_n3-group-vertical_0_phone.png
compare | OK: Groupe de boutons touch 01046322484_Groupe_de_boutons_touch_0_n3-group-vertical_1_tablet_v.png
compare | OK: Groupe de boutons touch 01046322484_Groupe_de_boutons_touch_0_n3-group-vertical_2_tablet_h.png
compare | ERROR: Tous les headings 01046322484_Tous_les_headings_0_n3-doc-heading_0_phone.png
   See: C:\Projets\N3\fwd-webapp-overlay-skin\backstop_data\bitmaps_test\light\20161004-135045\failed_diff_01046322484_Tous_les_headings_0_n3-doc-heading_0_phone.png
compare | OK: Tous les headings touch 01046322484_Tous_les_headings_touch_0_n3-doc-heading_0_phone.png
compare | ERROR: Tous les headings 01046322484_Tous_les_headings_0_n3-doc-heading_1_tablet_v.png
   See: C:\Projets\N3\fwd-webapp-overlay-skin\backstop_data\bitmaps_test\light\20161004-135045\failed_diff_01046322484_Tous_les_headings_0_n3-doc-heading_1_tablet_v.png
compare | OK: Tous les headings touch 01046322484_Tous_les_headings_touch_0_n3-doc-heading_1_tablet_v.png
compare | ERROR: Tous les headings 01046322484_Tous_les_headings_0_n3-doc-heading_2_tablet_h.png
   See: C:\Projets\N3\fwd-webapp-overlay-skin\backstop_data\bitmaps_test\light\20161004-135045\failed_diff_01046322484_Tous_les_headings_0_n3-doc-heading_2_tablet_h.png
compare | OK: Tous les headings touch 01046322484_Tous_les_headings_touch_0_n3-doc-heading_2_tablet_h.png
 report |
          Test completed...
 report | 63 Passed
 report | 3 Failed

 report | Writing browser report
 report | Browser reported copied
 report | Copied configuration to: C:\Projets\N3\fwd-webapp-overlay-skin\backstop_data\html_report\config.js
COMMAND | Executing core for `openReport`
openReport | Opening report.
   COMMAND | Command `openReport` sucessfully executed
    report | *** Mismatch errors found ***
    report | For a detailed report run `backstop openReport`

   COMMAND | Command `report` ended with an error
   COMMAND | Error: Mismatch errors found.
                 at C:\Users\ddu2949\AppData\Roaming\npm\node_modules\backstopjs\core\command\report.js:110:17
                 at lib$es6$promise$$internal$$tryCatch (C:\Users\ddu2949\AppData\Roaming\npm\node_modules\backstopjs\node_modules\phantomjs-prebuilt\node_modules\es6-promise\dist\es6-promise.js:362:1
6)
                 at lib$es6$promise$$internal$$invokeCallback (C:\Users\ddu2949\AppData\Roaming\npm\node_modules\backstopjs\node_modules\phantomjs-prebuilt\node_modules\es6-promise\dist\es6-promise.js
:374:17)
                 at lib$es6$promise$$internal$$publish (C:\Users\ddu2949\AppData\Roaming\npm\node_modules\backstopjs\node_modules\phantomjs-prebuilt\node_modules\es6-promise\dist\es6-promise.js:345:11
)
                 at lib$es6$promise$asap$$flush (C:\Users\ddu2949\AppData\Roaming\npm\node_modules\backstopjs\node_modules\phantomjs-prebuilt\node_modules\es6-promise\dist\es6-promise.js:119:9)
                 at doNTCallback0 (node.js:417:9)
                 at process._tickCallback (node.js:346:13)
   COMMAND | Command `test` ended with an error
   COMMAND | Error: Mismatch errors found.
                 at C:\Users\ddu2949\AppData\Roaming\npm\node_modules\backstopjs\core\command\report.js:110:17
                 at lib$es6$promise$$internal$$tryCatch (C:\Users\ddu2949\AppData\Roaming\npm\node_modules\backstopjs\node_modules\phantomjs-prebuilt\node_modules\es6-promise\dist\es6-promise.js:362:1
6)
                 at lib$es6$promise$$internal$$invokeCallback (C:\Users\ddu2949\AppData\Roaming\npm\node_modules\backstopjs\node_modules\phantomjs-prebuilt\node_modules\es6-promise\dist\es6-promise.js
:374:17)
                 at lib$es6$promise$$internal$$publish (C:\Users\ddu2949\AppData\Roaming\npm\node_modules\backstopjs\node_modules\phantomjs-prebuilt\node_modules\es6-promise\dist\es6-promise.js:345:11
)
                 at lib$es6$promise$asap$$flush (C:\Users\ddu2949\AppData\Roaming\npm\node_modules\backstopjs\node_modules\phantomjs-prebuilt\node_modules\es6-promise\dist\es6-promise.js:119:9)
                 at doNTCallback0 (node.js:417:9)
                 at process._tickCallback (node.js:346:13)

C:\Projets\N3\fwd-webapp-overlay-skin>
```

**Comment by garris** [comment]
Ok. I think you found a real live bug!  I will try to look at this on the train home.  Thank you for reporting.

**Comment by ricardosimoes** [comment]
I'm also experiencing this issue.

**Comment by fabioduque** [comment]
Same here!

**Comment by garris** [comment]
Is everyone on windows?

**Comment by fabioduque** [comment]
@garris Yes, I'm using it on Windows

**Comment by ricardosimoes** [comment]
I'm also using Windows

**Comment by garris** [comment]
Ok.  Sorry guys.  I am fairly certain this is a win only issue.   My guess is that somewhere in the codebase we may be looking for a (string[0] === '/') to test for relative paths -- or something like that.   Any help on this would be greatly appreciated as I am totally slammed today!  Thanks!  GS

**Comment by Spydr331** [comment]
I get the same issue as stephenbe, right down to the url.  I copied the two urls that the code is pointing to from the inspector tool to see how the browser is trying to translate the link:

`file:///C:/Users/mfeola/Desktop/backstop%20tests/C:/Users/mfeola/Desktop/backstop%20tests/backstop_data/bitmaps_test/20161005-113215/failed_diff_prod_test_Local_StyleGuide_0_doc-colors_0_phone.png`

`file:///C:/Users/mfeola/Desktop/backstop%20tests/backstop_data/bitmaps_test/20161005-113215/prod_test_Local_StyleGuide_0_doc-colors_0_phone.png`

The ../../ seems to be adding in the base url of **C:/Users/mfeola/Desktop/backstop%20tests/** twice

and the URL thats being called for the images comes from **thisTestPair.c.src** but i dont know enough about npm to edit this :(

**Comment by Spydr331** [comment]
also in the config.js files in the html_report folder, the reference and test images both start at the folders starting with "bitmaps_" but the diffImage starts at C:

```
"reference": "..\\bitmaps_reference\\prod_test_Local_StyleGuide_0_doc-colors_2_tablet_h.png"
"test": "..\\bitmaps_test\\20161005-113215\\prod_test_Local_StyleGuide_0_doc-colors_2_tablet_h.png"
"diffImage": "..\\..\\C:\\Users\\mfeola\\Desktop\\backstop tests\\backstop_data\\bitmaps_test\\20161005-113215\\failed_diff_prod_test_Local_StyleGuide_0_doc-colors_2_tablet_h.png"
```

**Comment by fabioduque** [comment]
@Spydr331 The config.js file is created dynamically, so although the browser is feeding from those values (specifically the wrong "diffImage" value), the problem comes from the file which generates config.js.

I will try also to take a look at the source code.

**Comment by garris** [comment]
Boom!  Found it...
https://github.com/garris/BackstopJS/blob/master/core/command/report.js#L24

**Comment by fabioduque** [comment]
@garris Nice!!!

**Comment by garris** [comment]
Patched here...
https://github.com/garris/BackstopJS/commit/e59728ad15e5f79571ffbc7ae777376f5d2fb70f

I just pushed it to master -- from my iPad -- on the subway.  Can someone verify?

**Comment by stephenbe** [comment]
Will do, give me 5-10 minutes

Amazing support, thanks @garris I really don't take it for granted!!

**Comment by fabioduque** [comment]
Already getting latest version and testing...I'll get back to you! Thanks for the quick fix!

**Comment by garris** [comment]
Well, I guess it's pretty good for free software!  😆

**Comment by stephenbe** [comment]
@garris  I just testing by changing it by hand, and it stills comes with two ../../ extra

**Comment by fabioduque** [comment]
It works!!! :D
Awesome!

@stephenbe Make sure you're changing the right file. I changed report.js from my main Node installation path, not from the node_modules inside my project.

Just to clarify, I changed it here (please note that I'm using Nodist):
C:\Nodist\bin\node_modules\backstopjs\core\command\report.js

**Comment by garris** [comment]
Rats.   :(   

As long as you're in there you could also do this to see if that is the issue...
https://github.com/garris/BackstopJS/commit/dcacb60fc38db6911f745bf695ae8faa921ddffe

**Comment by stephenbe** [comment]
@fabioduque oh right good point let me try that!. @garris don<t worry, it might be my fault

**Comment by fabioduque** [comment]
![image](https://cloud.githubusercontent.com/assets/2906992/19124207/2354aa36-8b2a-11e6-9b9f-84d7ec9bcb1c.png)

**Comment by garris** [comment]
@stephenbe @fabioduque Brilliant teamwork!!!   You guys rock -- thank you for the help!    I will push a revision after I get out of my AM meetings.

**Comment by stephenbe** [comment]
@garris @fabioduque it works!!! Thank you so much! Good team work, I agree!

**Comment by fabioduque** [comment]
@garris @stephenbe  Awesome fix and more points for you, for fixing it on the move!! I agree also with the teamwork! That's why open source will ALWAYS be better! :D Cheers for all!

**Comment by ricardosimoes** [comment]
You rock! 🚀
