### ISSUE TITLE
backstopjs Error

### ISSUE THREAD

**Issue by jedybeavis** [garris/BackstopJS#328]
See: /Users/Beavis/Desktop/Auto_testing/Новая папка 2/test_img/20161026-093054/failed_diff_ATD_Home_0_wrapper_0_orig.png
compare | ERROR { size: isDifferent, content: 3.35%, threshold: 1% }: Bremsscheibe ATD_Bremsscheibe_0_wrap_content_0_orig.png
   See: /Users/Beavis/Desktop/Auto_testing/Новая папка 2/test_img/20161026-093054/failed_diff_ATD_Bremsscheibe_0_wrap_content_0_orig.png
compare | OK: Autoteile ATD_Autoteile_0_wrap_content_0_orig.png
 report | 
          Test completed...
 report | 2 Passed
 report | 3 Failed
          
 report | Writing browser report
 report | Browser reported copied
 report | Copied configuration to: /Users/Beavis/Desktop/Auto_testing/Новая папка 2/html_report/config.js
COMMAND | Executing core for `openReport`
openReport | Opening report.
   COMMAND | Command `openReport` sucessfully executed
    report | *** Mismatch errors found ***
    report | For a detailed report run `backstop openReport`
             
   COMMAND | Command `report` ended with an error
   COMMAND | Error: Mismatch errors found.
                 at /Users/Beavis/Desktop/Auto_testing/Новая папка 2/node_modules/backstopjs/core/command/report.js:108:17
   COMMAND | Command `test` ended with an error
   COMMAND | Error: Mismatch errors found.
                 at /Users/Beavis/Desktop/Auto_testing/Новая папка 2/node_modules/backstopjs/core/command/report.js:108:17

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! backstopjs@2.0.6 test: `node ./cli/index.js test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the backstopjs@2.0.6 test script 'node ./cli/index.js test'.
npm ERR! This is most likely a problem with the backstopjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./cli/index.js test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs backstopjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls backstopjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Beavis/Desktop/Auto_testing/Новая папка 2/node_modules/backstopjs/npm-debug.log

**Comment by mirzazeyrek** [comment]
same here

**Comment by Primajin** [comment]
Sorry guys, what is the problem? So backstop finds mismatch errors - that means you changed something according to the last reference file.

 { size: isDifferent, content: 3.35%, threshold: 1% }

Means: The Size of the Screenshots is already different plus the content is off by 3,35% - where 1% off was the threshold under it would have passed.

**Comment by mirzazeyrek** [comment]
Throwing an error breaks CI process but I have found a workaround. That's okey.

**Comment by Primajin** [comment]
But that is what it's meant for! It must break your CI process, since evidently your style is wrong. If you changed the style on purpose you need to check in new references into your repo.

**Comment by mirzazeyrek** [comment]
First objection: It could be a false positive. 
Second objection: If I have like 50 test cases on 5 different resolutions. I would like to see a full report about everything in the end of the process. instead of only seeing 1 bug. Seeing other ones could be more helpful.

**Comment by garris** [comment]
@mirzazeyrek If you get a chance, I am curious how you solved the issue.  It may be something we could add to the documentation to help other users.

**Comment by mirzazeyrek** [comment]
Dear Garris,

With Jenkins what I needed to do is this:

backstop reference --configPath=chrome_blog_portfolio_15_08_2016_08_43_14.json || true
backstop test --configPath=chrome_blog_portfolio_15_08_2016_08_43_14.json || true

Even there are errors it won't break the entire job or chained jobs.

![screenshot_70](https://cloud.githubusercontent.com/assets/6233650/20299475/c2db3930-ab23-11e6-9093-fb27ae02e98a.png)

**Comment by garris** [comment]
Wow -- yes, very very nice!   Thanks for sharing -- I will add this to the documentation.  👍

**Comment by rasenplanscher** [comment]
I'm basically with @Primajin here. What's the value of running `reference` before `test`? That way you will always have passes.... You could just as well remove backstop from your build and be done a lot faster... What am I missing?

**Comment by garris** [comment]
@rasenplanscher FWIW:  There are two options for handling new changes.

1) if you run `backstop test [--filter=<someScenarioLabel>]` for an existing scenario and you want to keep those changes you can immediately run `backstop approve`.  This will _promote_ all your previously-failed screenshot(s) to be the new reference.  

2) if you have not already created a reference for a new scenario you can run `backstop reference --filter=<someScenarioLabel>`.  This will create a reference for that scenario only.

Using these two approaches you can help you update your references incrementally without concern for other unchecked scenario issues.

**Comment by rasenplanscher** [comment]
@garris I do understand that. What I don't get is the value of what @mirzazeyrek does:
```
backstop reference --configPath=chrome_blog_portfolio_15_08_2016_08_43_14.json || true
backstop test --configPath=chrome_blog_portfolio_15_08_2016_08_43_14.json || true
```
He uses the same config file for both `reference` and `test`, in that order. That means, no matter what happens during his test session, he will always receive the same images as are already in his references. Therefore he can never have failing tests. And that means his tests are fully moot.

**Comment by garris** [comment]
@rasenplanscher Oh right, I see what you are saying.   It was the || (double pipe) that I thought was cool there.   I think he was just looking for a way to not break CI just because Backstop found an error -- which seems like a reasonable option (e.g. a quick way for a report-only integration).   

FWIW:  I don't know exactly how running `reference` and then `test` would be useful IRL -- but @mirzazeyrek has done some really great work for BackstopJS so I just kind of assumed it was a quick example.

**Comment by rasenplanscher** [comment]
OK, I see 🤔 

@mirzazeyrek Care to elaborate?

**Comment by mirzazeyrek** [comment]
@rasenplanscher I am not sure if I followed. What makes you think tests will always pass ? We are still using this approach and just yesterday we had 131 failed tests.

![image](https://cloud.githubusercontent.com/assets/6233650/25985984/29febd4a-36f6-11e7-89a5-d68f39756cc0.png)

Only scenario that I think tests will always pass is using same URL both for reference and for test web site. And that makes no sense for CI and Jenkins integration.

What I am doing is for example:

Reference URL: reference.yourdomain.com

Test URL: jenkins-build-id.yourdomain.com


May be don't need to mention but of course it will fail if you do:

Reference URL: reference.yourdomain.com
Test URL: reference.yourdomain.com

**Comment by rasenplanscher** [comment]
@mirzazeyrek 
Ah, yes. I thought you were pointing the tests to the same URLs as the reference since you use the same config file for both reference and test. I didn't think of the `referenceUrl` setting. Now, it gels 👍 thank you!

**Comment by Primajin** [comment]
Ahhh! I was also on the wrong track like @rasenplanscher . Thanks @mirzazeyrek for clearing that!

**Comment by leonardws** [comment]
/Users/Beavis :)
