### ISSUE TITLE
CasperJS' test suite within BackstopJS?

### ISSUE THREAD

**Issue by boriskaiser** [garris/BackstopJS#412]
Hello,

can I use CasperJS' test suite within BackstopJS?
I have written a simple test, but unfortunately this always fails.

*FYI I use the last version of BackstopJS (2.6.6).*

`onReady.js`
```js
module.exports = function (casper, scenario, vp) {
    casper.echo('assertEquals test - START');
    casper.test.begin('assertEquals() tests', 3, function (test) {
        test.assertEquals(1 + 1, 2);
        test.assertEquals([1, 2, 3], [1, 2, 3]);
        test.assertEquals({a: 1, b: 2}, {a: 1, b: 2});
        test.done();
    });
    casper.echo('assertEquals test - END');
};
```

**Console output**

```bash
CasperJS:  assertEquals test - START
CasperJS:  [debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true
CasperJS:  [debug] [phantom] url changed to "about:blank"

Testing script failed with code: 1

An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
COMMAND | Command `test` ended with an error
COMMAND | Error: An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
              at ChildProcess.<anonymous> (/Users/boriskaiser/Sites/backstopjs-casper-test/node_modules/backstopjs/core/util/createBitmaps.js:70:18)
              at emitTwo (events.js:106:13)
              at ChildProcess.emit (events.js:191:7)
              at maybeClose (internal/child_process.js:877:16)
              at Socket.<anonymous> (internal/child_process.js:334:11)
              at emitOne (events.js:96:13)
              at Socket.emit (events.js:188:7)
              at Pipe._handle.close [as _onclose] (net.js:498:12)

npm ERR! Darwin 16.4.0
npm ERR! argv "/Users/boriskaiser/.nvm/versions/node/v6.9.1/bin/node" "/Users/boriskaiser/.nvm/versions/node/v6.9.1/bin/npm" "run" "test:visual"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! backstopjs-casper-test@2.0.0 test:visual: `backstop test --configPath=test/visual/backstop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the backstopjs-casper-test@2.0.0 test:visual script 'backstop test --configPath=test/visual/backstop'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the backstopjs-casper-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     backstop test --configPath=test/visual/backstop
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs backstopjs-casper-test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls backstopjs-casper-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/boriskaiser/Sites/backstopjs-casper-test/npm-debug.log
```

**Comment by garris** [comment]
Sorry.  You can't do that.   I think `casper.test` will probably bork everything.  But it could probably be integrated in some way.  Would take a lot of thought.

**Comment by boriskaiser** [comment]
@garris 
Thx!
