### ISSUE TITLE
Error using config object

### ISSUE THREAD

**Issue by Enchiridion** [garris/BackstopJS#415]
I've been unable to get backstop to work by passing a config object instead of a path to a config file (which I can get to work, but is sub-optimal).  Even using the example in the readme fails:

```
var gulp         = require('gulp')
,   backstop     = require('backstopjs')
;

gulp.task('test-css', function() {
    backstop('test', {
      config: {
        id: "foo",
        scenarios: [
          //some scenarios here
        ]
      }
    });
});
```

Output:
```
λ gulp test-css
(node:5188) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[10:55:01] Using gulpfile ~\Sites\itc.visitidaho\gulpfile.js
[10:55:01] Starting 'test-css'...
[10:55:01] 'test-css' errored after 1.47 ms
[10:55:01] TypeError: Path must be a string. Received { id: 'foo', scenarios: [] }
    at assertPath (path.js:7:11)
    at Object.isAbsolute (path.js:439:5)
    at loadProjectConfig (C:\Users\slittle\Sites\itc.visitidaho\node_modules\backstopjs\core\util\makeConfig.js:22:14)
    at makeConfig (C:\Users\slittle\Sites\itc.visitidaho\node_modules\backstopjs\core\util\makeConfig.js:59:20)
    at module.exports (C:\Users\slittle\Sites\itc.visitidaho\node_modules\backstopjs\core\runner.js:5:16)
    at Gulp.<anonymous> (C:\Users\slittle\Sites\itc.visitidaho\gulpfile.js:6:5)
    at module.exports (C:\Users\slittle\Sites\itc.visitidaho\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\slittle\Sites\itc.visitidaho\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\slittle\Sites\itc.visitidaho\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\slittle\Sites\itc.visitidaho\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
```

It looks like in makeConfig.js:20 it always assumes options.config is a file path?

node v6.10.0
npm v4.3.0
backstopjs v2.6.7

**Comment by garris** [comment]
@Enchiridion Thanks for reporting!   Sorry bout that. 

@skip405 -- I think this was your feature.  Could you maybe take a look?   

Thanks guys!

**Comment by garris** [comment]
Pull was here..  https://github.com/garris/BackstopJS/pull/386

**Comment by skip405** [comment]
@garris some parts were lost in resolving the conflicts. In my PR the `options.config` is removed from the check and added later. Shall I create another PR?

**Comment by skip405** [comment]
@Enchiridion sorry to hear it, my PR was partly merged and I failed to notice the missing bit :(

A quick fix for you will be to grab lines 14-18 of [this diff](https://github.com/garris/BackstopJS/pull/386/commits/d7c7e7097ebd2d185815a4ad49ec3a5d4621188e#diff-3bd36b870899be829f28e9af5d49bb00) and patch your `makeConfig`... I know it's not ideal, but maybe you'll be able to get by until a new patch version is released.

**Comment by garris** [comment]
Oh crap.  Did I hose the merge?  Sorry!   Yes please add that pull request against canary.  I will get that out today!

**Comment by garris** [comment]
@skip405 Also,  Thanks for the quick response!

**Comment by skip405** [comment]
@garris no worries ;) A question though, is it best to PR from `canary` to `canary` or from `master` to `canary`? I first tried `master`, but there's a lot to merge then (with conflicts )) ). Are you OK with `canary` to `canary`?

**Comment by Enchiridion** [comment]
@skip405 Np. Patching those lines fixed the issue.  Really appreciate the fast response on this!

**Comment by garris** [comment]
Sorry man,  the branches got out of sync last week.   I just brought them all to parity so you may have to rebase what you can and just add the edit as a new commit.   You can put the patch wherever you like.  I will publish it and push it to the other branches.

**Comment by skip405** [comment]
@garris please take a look - #416 - made it from `canary`

**Comment by garris** [comment]
I published this out.  You can install via `npm install -g backstopjs@canary`

If anyone wants to validate that would be great.   I'll push this out to @latest later today.

Thanks @skip405 and @Enchiridion -- really appreciate the report and quick turnaround!  👍

**Comment by Enchiridion** [comment]
Working for me using canary

**Comment by garris** [comment]
Great.  Pushed to @latest.    Thanks!
