### ISSUE TITLE
Couldn't start backstop as a child process

### ISSUE THREAD

**Issue by marciovicente** [garris/BackstopJS#430]
I'm trying to use backstopjs into a express application. I'm creating dynamically configuration file using original file just overwriting the scenario (I wanna run just to one scenario in this case). So here the problem happens.

```javascript
const createReference = (newSpec) => {
  const originalConfigFile = require('../tests/config.json');

  const tmpFile = '/tmp/new-config.json';
  const referencesPath = '/tmp/references';

  const newConfig = {
    ...omit(originalConfigFile, ['onBeforeScript', 'onReadyScript', 'scenarios', 'paths.bitmaps_reference']),
    scenarios: [newSpec],
    paths: {
      bitmaps_reference: "/tmp/references",
      bitmaps_test: "/tmp/bitmaps_test",
      casper_scripts: "/tmp/casper_scripts",
      html_report: "/tmp/html_report",
      ci_report: "/tmp/ci_report",
    }
  };

  fs.writeFile(tmpFile, JSON.stringify(newConfig, null, 2), (err) => {
    exec(`backstop reference --configPath=${tmpFile}`, (err, stdout, stderr) => {
      if (err) {
        console.log(stdout);
        return;
      }
      // do something else
    });
  });
}
```

When I run this same code (`backstop reference --configPath=/tmp/new-config.json`) separately from my express application, it's sounds good, but in child process it returns:

```shell
BackstopJS loading config:  /tmp/new-spec.json

COMMAND | Executing core for `reference`
  clean | /tmp/references was cleaned.

Running CasperJS with:  [ '/Users/marciovicente/git/test-project/node_modules/backstopjs/capture/genBitmaps.js',
  '--engine=slimerjs',
  '--captureConfigFileName=/var/folders/m_/ydbqsgh94vlf0dwk_n1cfhv40000gn/T/capture/75b3b173ef6003982053521774d69d83008ea8e6.json' ]
CasperJS:  Debug is enabled!
CasperJS:  CREATING NEW REFERENCE FILES

Testing script failed with code: 1

An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
COMMAND | Command `reference` ended with an error
COMMAND | Error: An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
              at ChildProcess.<anonymous> (/Users/marciovicente/git/test-project/node_modules/backstopjs/core/util/createBitmaps.js:70:18)
              at emitTwo (events.js:106:13)
              at ChildProcess.emit (events.js:194:7)
              at maybeClose (internal/child_process.js:899:16)
              at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

I've already tried to use the backstop package instead of run binary from child process but the error still happens.

Here is my config output (from `/tmp/new-config.json`)
```json
{  
   "id":"prod_test",
   "viewports":[  
      {  
         "name":"default",
         "width":1024,
         "height":768
      }
   ],
   "readyEvent":null,
   "delay":500,
   "misMatchThreshold":0.1,
   "paths":{  
      "bitmaps_reference":"/tmp/references",
      "bitmaps_test":"/tmp/bitmaps_test",
      "casper_scripts":"/tmp/casper_scripts",
      "html_report":"/tmp/html_report",
      "ci_report":"/tmp/ci_report"
   },
   "casperFlags":[  

   ],
   "engine":"slimerjs",
   "report":[  
      "CI"
   ],
   "debug":true,
   "scenarios":[  
      {  
         "label":"Google",
         "url":"http://google.com"
      }
   ]
}
```

**Comment by marciovicente** [comment]
@garris could you take a quick look here? Pls! 😬 🙏

**Comment by garris** [comment]
have you tried this approach?

https://github.com/garris/BackstopJS#you-can-pass-a-config-object-directly

**Comment by marciovicente** [comment]
Yep, as I've mentioned before. The code below generates the same output.
```javascript
  backstop('reference', { config: newConfig })
    .catch(err => console.error(err))
    .then(ok => console.log('>>>>>>', ok));
```

```bash
BackstopJS uses a passed object as config
COMMAND | Executing core for `reference`
  clean | /tmp/references was cleaned.

Running CasperJS with:  [ '/Users/marciovicente/git/dali/node_modules/backstopjs/capture/genBitmaps.js',
  '--engine=slimerjs',
  '--captureConfigFileName=/var/folders/m_/ydbqsgh94vlf0dwk_n1cfhv40000gn/T/capture/6b1961b5474ed3ab4d38a58d00847ea84af8f478.json' ]
CasperJS:  Debug is enabled!
CasperJS:
CasperJS:  CREATING NEW REFERENCE FILES
CasperJS:

Testing script failed with code: 1

An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
COMMAND | Command `reference` ended with an error
COMMAND | Error: An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
              at ChildProcess.<anonymous> (/Users/marciovicente/git/dali/node_modules/backstopjs/core/util/createBitmaps.js:70:18)
              at emitTwo (events.js:106:13)
              at ChildProcess.emit (events.js:194:7)
              at maybeClose (internal/child_process.js:899:16)
              at Socket.<anonymous> (internal/child_process.js:342:11)
              at emitOne (events.js:96:13)
              at Socket.emit (events.js:191:7)
              at Pipe._handle.close [as _onclose] (net.js:513:12)
Error: An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
    at ChildProcess.<anonymous> (/Users/marciovicente/git/dali/node_modules/backstopjs/core/util/createBitmaps.js:70:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:513:12)
>>>>>> undefined
```

PS: If this method returns a promise and (probably) the process rejects it, why `.ok => console.log('>>>>>', ok)` code is being executed?

**Comment by garris** [comment]
So sorry, I am not seeing anything obviously wrong.   Maybe an error getting swallowed.   Are you able to just run the simple jsBasedConfig by importing from the /examples directory?

**Comment by klausbayrhammer** [comment]
Probably it's the child process' changed cwd? Or any ENVs changed?

**Comment by marciovicente** [comment]
Ok guys, I figured out what's happening.. I don't know the reason, but the problem is when I'm running with `slimerjs`.
I chose slimer to support all new frameworks (React client side render, for example). So, I'll close this issue, and thank you for your attention @klausbayrhammer @garris :)
