### ISSUE TITLE
Issue using Slimer JS on Windows 10

### ISSUE THREAD

**Issue by AndrewLeedham** [garris/BackstopJS#431]
I'm trying to use slimerjs with backstopjs through gulp. I'm on Win10. I have slimerjs installed via npm globally. My current setup works fine when using PhantomJS. 

BackstopJS version: 2.6.11
SlimerJS version: 0.10.3

```
Error: An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
    at ChildProcess.<anonymous> (C:\Users\W53MYBJ3\Documents\GitHub\xerox.com\xerox-framework\node_modules\backstopjs\core\util\createBitmaps.js:70:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
[10:51:02] 'patternlab:build' errored after 158 ms
[10:51:02] Error in plugin 'run-sequence(testing-setup:backstop)'
Message:
    An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
Stack:
Error: An unexpected error occured. You may want to try setting the debug option to `true` in your config file.
    at ChildProcess.<anonymous> (C:\Users\W53MYBJ3\Documents\GitHub\xerox.com\xerox-framework\node_modules\backstopjs\core\util\createBitmaps.js:70:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

My backstop.json is as follows:
```
{
  "id": "component_tests",
  "viewports": [
    {
      "name": "phone",
      "width": 320,
      "height": 480
    },
    {
      "name": "tablet_v",
      "width": 568,
      "height": 1024
    },
    {
      "name": "tablet_h",
      "width": 1024,
      "height": 768
    }
  ],
  "scenarios": [
    {
      "label": "CTA Button",
      "url": "http://localhost:3000/patterns/00-atoms-buttons-button/00-atoms-buttons-button.rendered.html",
      "hideSelectors": [],
      "removeSelectors": [],
      "selectorExpansion": true,
      "selectors": [
        ".c-btn"
      ],
      "readyEvent": null,
      "delay": 500,
      "misMatchThreshold" : 0.1
    },
    {
      "label": "CTA Button Hover",
      "url": "http://localhost:3000/patterns/00-atoms-buttons/index.html",
      "hideSelectors": [],
      "removeSelectors": [],
      "selectorExpansion": true,
      "selectors": [
        ".c-cta",
        ".c-btn"
      ],
      "readyEvent": null,
      "delay": 500,
      "misMatchThreshold" : 0.1
    }
  ],

  
  "paths": {
    "bitmaps_reference": "./backstop_data/bitmaps_reference",
    "bitmaps_test": "./backstop_data/bitmaps_test",
    "casper_scripts": "./backstop_data/casper_scripts",
    "html_report": "./backstop_data/html_report",
    "ci_report": "./backstop_data/ci_report"
  },
  "casperFlags": [],
  "engine": "slimerjs",
  "report": ["browser"],
  "debug": false
}
```

And the gulp command I am running is as follows:
```
gulp.task('testing-setup:backstop', function(cb){
  return backstop('reference');
});
```

I have tried setting the SLIMERJS_EXECUTABLE envar, to no avail. Any insight would be much appreciated?

**Comment by garris** [comment]
Hmmm.  Sorry -- no clue what's going on there.   Are you able to run with slimer using the default config?  It may be a BackstopJS/slimer bug when imported.

**Comment by AndrewLeedham** [comment]
Tried it with a completely stripped down version, didn't change anything. 

However I've tried to run this through a vagrant box running linux, but I'm running in to a different issue that seems more fixable. 
`Error: GDK_BACKEND does not match available displays`
This makes sense since it is a virtual machine with no displays, the fix on SlimerJS's end is to run the command with xvbf, BackstopJS doesn't seem to be doing this, is this a bug, or is there some config option I'm missing?

**Comment by garris** [comment]
You might have to hack that one yourself.   BackstopJS doesn't talk directly to slimer -- it's all going through casperjs.   Sorry I can't help beyond this.   Please post back here if you can figure it out -- might be useful for others. 

Best, Garris
