### ISSUE TITLE
Viewports width broken using Drone.io CI 

### ISSUE THREAD

**Issue by NimaSoroush** [garris/BackstopJS#465]
Hi,

Just tried to integrate backstopJs with [Drone.io](https://github.com/drone/drone) and when viewport width goes higher than some numbers it will break the tests. The Same test will pass locally.
Here is my config:

```
module.exports = {
  id: 'prod_test',
  viewports: [
    {
      name: 'browser',
      width: 1366,
      height: 768,
    },
  ],
  scenarios: [
    {
      label: 'Default',
      url: 'http://localhost:3000/',
      hideSelectors: [],
      removeSelectors: [],
      selectorExpansion: true,
      selectors: [
        '#root',
      ],
      readyEvent: null,
      delay: 500,
      misMatchThreshold: 0.1,
      requireSameDimensions: true,
    },
  ],
  paths: {
    bitmaps_reference: 'src/visualTests/backstop_data/bitmaps_reference',
    bitmaps_test: 'src/visualTests/backstop_data/bitmaps_test',
    html_report: 'src/visualTests/backstop_data/html_report',
    ci_report: 'src/visualTests/backstop_data/ci_report',
  },
  ci: {
    format: 'junit',
  },
  casperFlags: [],
  engine: 'phantomjs',
  report: ['CI'],
  debug: false,
};
```

Any idea why that would happen?
Thanks

**Comment by garris** [comment]
Can you send screenshots from the report?  Including console output?

**Comment by NimaSoroush** [comment]
It is in CI mode, so no screenshots on Drone pipeline, but here is the report:

```
console.log node_modules/backstopjs/core/util/makeConfig.js:39
      BackstopJS uses a passed object as config
    console.log node_modules/backstopjs/core/util/logger.js:63
      COMMAND | Executing core for `test`
    console.log node_modules/backstopjs/core/util/runCasper.js:31
      
      Running CasperJS with:  [ '/drone/src/git.prod.website.local/web-platform/header/node_modules/backstopjs/capture/genBitmaps.js',
        '--captureConfigFileName=/drone/src/git.prod.website.local/web-platform/header/capture/9b41f8fd00904b1da5077b2502bad7bddd5a07c9.json' ]
    console.log node_modules/backstopjs/core/util/runCasper.js:40
      CasperJS:  Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
    console.log node_modules/backstopjs/core/util/runCasper.js:40
      CasperJS:  Ready event received.
    console.log node_modules/backstopjs/core/util/runCasper.js:40
      CasperJS:  Current location is http://localhost:3000/
    console.log node_modules/backstopjs/core/util/runCasper.js:40
      CasperJS:  Capturing screenshots for phone (320x480)
    console.log node_modules/backstopjs/core/util/runCasper.js:40
      CasperJS:  Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
    console.log node_modules/backstopjs/core/util/runCasper.js:40
      CasperJS:  Ready event received.
    console.log node_modules/backstopjs/core/util/runCasper.js:40
      CasperJS:  Current location is http://localhost:3000/
    console.log node_modules/backstopjs/core/util/runCasper.js:40
      CasperJS:  Capturing screenshots for browser (1366x768)
    console.log node_modules/backstopjs/core/util/runCasper.js:40
      CasperJS:  Comparison config file updated.
    console.log node_modules/backstopjs/core/util/createBitmaps.js:66
      
      Bitmap file generation completed.
    console.log node_modules/backstopjs/core/util/logger.js:63
      COMMAND | Executing core for `report`
    console.log node_modules/backstopjs/core/util/logger.js:63
      compare | OK: Header with default configs prod_test_Header_with_default_configs_0_header-root_0_phone.png
    console.log node_modules/backstopjs/core/util/logger.js:63
      compare | ERROR { requireSameDimensions: false size: ok, content: 3.33%, threshold: 0.1% }: Header with default configs prod_test_Header_with_default_configs_0_header-root_1_browser.png
    console.log node_modules/backstopjs/core/util/compare/store-failed-diff.js:7
         See: /drone/src/git.prod.website.local/web-platform/backstop_data/bitmaps_test/20170622-101230/failed_diff_prod_test_Header_with_default_configs_0_header-root_1_browser.png
    console.log node_modules/backstopjs/core/util/logger.js:63
       report | Test completed...
    console.log node_modules/backstopjs/core/util/logger.js:63
       report | 1 Passed
    console.log node_modules/backstopjs/core/util/logger.js:63
       report | 1 Failed
    console.log node_modules/backstopjs/core/util/logger.js:63
       report | Writing jUnit Report
    console.log node_modules/backstopjs/core/util/logger.js:63
       report | Writing browser report
    console.log node_modules/backstopjs/core/util/logger.js:63
       report | jUnit report written to: ../backstop_data/ci_report/xunit.xml
    console.log node_modules/backstopjs/core/util/logger.js:63
       report | Browser reported copied
    console.log node_modules/backstopjs/core/util/logger.js:63
       report | Copied configuration to: /drone/src/git.prod.website.local/web-platform/backstop_data/html_report/config.js
    console.log node_modules/backstopjs/core/util/logger.js:63
      COMMAND | Executing core for `openReport`
    console.log node_modules/backstopjs/core/util/logger.js:63
      openReport | Opening report.
    console.log node_modules/backstopjs/core/util/logger.js:63
      openReport | An error occured while opening report in the default browser.
    console.log node_modules/backstopjs/core/util/logger.js:63
         COMMAND | Command `openReport` sucessfully executed
    console.log node_modules/backstopjs/core/util/logger.js:63
          report | *** Mismatch errors found ***
    console.log node_modules/backstopjs/core/util/logger.js:63
          report | For a detailed report run `backstop openReport`
                   
    console.log node_modules/backstopjs/core/util/logger.js:63
         COMMAND | Command `report` ended with an error
    console.log node_modules/backstopjs/core/util/logger.js:63
         COMMAND | Error: Mismatch errors found.
                       at /drone/src/git.prod.website.local/web-platform/header/node_modules/backstopjs/core/command/report.js:113:17
                       at propagateAslWrapper (/drone/src/git.prod.website.local/web-platform/header/node_modules/async-listener/index.js:468:23)
                       at /drone/src/git.prod.website.local/web-platform/header/node_modules/async-listener/index.js:505:70
                       at /drone/src/git.prod.website.local/web-platform/header/node_modules/async-listener/glue.js:188:31
                       at propagateAslWrapper (/drone/src/git.prod.website.local/web-platform/header/node_modules/async-listener/index.js:468:23)
                       at /drone/src/git.prod.website.local/web-platform/header/node_modules/async-listener/index.js:505:70
                       at /drone/src/git.prod.website.local/web-platform/header/node_modules/async-listener/glue.js:188:31
                       at process._tickDomainCallback (internal/process/next_tick.js:129:7)
    console.log node_modules/backstopjs/core/util/logger.js:63
         COMMAND | Command `test` ended with an error
    console.log node_modules/backstopjs/core/util/logger.js:63
         COMMAND | Error: Mismatch errors found.
                       at /drone/src/git.prod.website.local/web-platform/header/node_modules/backstopjs/core/command/report.js:113:17
                       at propagateAslWrapper (/drone/src/git.prod.website.local/web-platform/header/node_modules/async-listener/index.js:468:23)
                       at /drone/src/git.prod.website.local/web-platform/header/node_modules/async-listener/index.js:505:70
                       at /drone/src/git.prod.website.local/web-platform/header/node_modules/async-listener/glue.js:188:31
                       at propagateAslWrapper (/drone/src/git.prod.website.local/web-platform/header/node_modules/async-listener/index.js:468:23)
                       at /drone/src/git.prod.website.local/web-platform/header/node_modules/async-listener/index.js:505:70
                       at /drone/src/git.prod.website.local/web-platform/header/node_modules/async-listener/glue.js:188:31
                       at process._tickDomainCallback (internal/process/next_tick.js:129:7)```

**Comment by garris** [comment]
Hi @NimaSoroush,  Sorry, but it is a little hard for me to figure out what is going on by just looking at this logout.   I am not seeing any red flags.   But if backstop is working for you using the default config it is possible that the issue may be caused by interaction with your app.

**Comment by NimaSoroush** [comment]
Hi @garris: Sorry for not providing enough info, unfortunately, this is all I get from Drone logs!

I don't think that the problem is the connection to my app as I can increase the width size to a certain amount. The latest one that passed was 

```
...
viewports: [
    {
      name: 'browser',
      width: 800,
      height: 1240,
    },
  ],
...
```

I am planning to debug this in local Drone and collect more logs/screenshots. Will update this issue when I have more info

**Comment by mirzazeyrek** [comment]
Are you sure this is a width issue ? Could it be font rendering difference ? 

@NimaSoroush
