### ISSUE TITLE
Config is not defined error running backstop test

### ISSUE THREAD

**Issue by sattaman** [garris/BackstopJS#481]
I am experiencing the following error with BackstopJS v3.0.4. 
backstop reference runs correctly, backstop test fails. My config is here 
https://gist.github.com/sattaman/95f1f9c01d4853bf6800c6a69390af83

```
C:\work\ParentPortal>backstop test
BackstopJS v3.0.4
Loading config:  C:\work\ParentPortal\backstop.json

COMMAND | Executing core for `test`
createBitmaps | Selcted 10 of 10 scenarios.
Starting Chromy: port:9222 [ '--window-size=320,480' ]
Starting Chromy: port:9223 [ '--window-size=1280,768' ]
Starting Chromy: port:9224 [ '--window-size=320,480' ]
Starting Chromy: port:9225 [ '--window-size=1280,768' ]
Starting Chromy: port:9226 [ '--window-size=320,480' ]
Starting Chromy: port:9227 [ '--window-size=1280,768' ]
Starting Chromy: port:9228 [ '--window-size=320,480' ]
Starting Chromy: port:9229 [ '--window-size=1280,768' ]
Starting Chromy: port:9230 [ '--window-size=320,480' ]
Starting Chromy: port:9231 [ '--window-size=1280,768' ]
      COMMAND | Command `test` ended with an error after [0.014s]
      COMMAND | ReferenceError: config is not defined
                    at getMisMatchThreshHold (C:\Users\SATTA-WORK\AppData\Roaming\npm\node_modules\backstopjs\core\util\runChromy.js:404:14)
                    at C:\Users\SATTA-WORK\AppData\Roaming\npm\node_modules\backstopjs\core\util\runChromy.js:299:28
                    at Array.map (native)
                    at delegateSelectors (C:\Users\SATTA-WORK\AppData\Roaming\npm\node_modules\backstopjs\core\util\runChromy.js:276:48)
                    at Promise (C:\Users\SATTA-WORK\AppData\Roaming\npm\node_modules\backstopjs\core\util\runChromy.js:246:15)
                    at processScenarioView (C:\Users\SATTA-WORK\AppData\Roaming\npm\node_modules\backstopjs\core\util\runChromy.js:227:10)
                    at module.exports (C:\Users\SATTA-WORK\AppData\Roaming\npm\node_modules\backstopjs\core\util\runChromy.js:27:10)
                    at Promise.resolve.then.el (C:\Users\SATTA-WORK\AppData\Roaming\npm\node_modules\backstopjs\node_modules\p-map\index.js:42:16)
                    at process._tickCallback (internal/process/next_tick.js:109:7)
                    at Module.runMain (module.js:606:11)
```

**Comment by sattaman** [comment]
i was missing the ,
      "misMatchThreshold" : 0.1 
in the config doh!
