### ISSUE TITLE
Mac installation errors with NPM

### ISSUE THREAD

**Issue by willenium** [garris/BackstopJS#501]
# Global installation
When trying to install the last version of Backstopjs **globally** the installation fails with the following error:
```
gyp verb build dir attempting to create "build" dir: /usr/local/lib/node_modules/backstopjs/node_modules/sharp/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/backstopjs/node_modules/sharp/build'
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/backstopjs/node_modules/sharp
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.18.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.``
```
I have tried to manually create the directory its trying to create but when I do it results in the same error.

# Local installation
And when trying to install the latest version of Backstopjs **locally** the installation also fails. 
The following output is shown:
```
gyp info spawn args   '-Goutput_dir=.' ]
/Users/username/Projects/projectname/node_modules/sharp/binding.js:34
    .extract({
     ^

TypeError: tar.extract is not a function
    at unpack (/Users/username/Projects/projectname/node_modules/sharp/binding.js:34:6)
    at WriteStream.<anonymous> (/Users/username/Projects/projectname/node_modules/sharp/binding.js:94:9)
    at emitNone (events.js:110:20)
    at WriteStream.emit (events.js:207:7)
    at finishMaybe (_stream_writable.js:601:14)
    at afterWrite (_stream_writable.js:453:3)
    at onwrite (_stream_writable.js:443:7)
    at fs.js:2133:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:691:5)
gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/username/Projects/projectname/node_modules/sharp
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.18.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Any idea how I can fix these?
I am on Node version `8.4.0` and on NPM version `5.3.0`.

**Comment by garris** [comment]
@willenium -- thanks for posting!   I just pushed up a new version with the sharp library removed.   Please try it again and let me know if it's working for you again. 
```
npm install -g backstopjs
```
 Thanks!

**Comment by willenium** [comment]
Nice it works now! Thanks @garris
