### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by digitalpencil** [garris/BackstopJS#509]
When attempting to run a chromy-based onReadyScript that envokes Chromy, I get the following error. It's coming from babel-polyfill and i've tried removing all other npm modules however the error persists. Is my attempt here wrong?

node --version
v6.11.0

onReady.js
```
const Chromy = require( 'chromy' );

module.exports = function ( engine, scenario, vp ) {
    const chromy = new Chromy().chain()
        .goto( 'https://github.com/garris/BackstopJS' )
        .close().end();
    console.log( 'running onReady');
};
```

Error:
```
backstop test --filter=header-footer
BackstopJS v3.0.14
Loading config:  /Users/dg/Sites/scratch/html/backstop.json

COMMAND | Executing core for `test`
createBitmaps | Selcted 1 of 11 scenarios.
Starting Chromy: port:9222 --window-size=320,1024
Starting Chromy: port:9223 --window-size=768,1024
Starting Chromy: port:9224 --window-size=1268,1024
      COMMAND | Command `test` ended with an error after [0.396s]
      COMMAND | Error: only one instance of babel-polyfill is allowed
                    at Object.<anonymous> (/Users/dg/Sites/scratch/html/node_modules/babel-polyfill/lib/index.js:10:9)
                    at Module._compile (module.js:570:32)
                    at Object.Module._extensions..js (module.js:579:10)
                    at Module.load (module.js:487:32)
                    at tryModuleLoad (module.js:446:12)
                    at Function.Module._load (module.js:438:3)
                    at Module.require (module.js:497:17)
                    at require (internal/module.js:20:19)
                    at Object.<anonymous> (/Users/dg/Sites/scratch/html/node_modules/async-chain-proxy/dist/index.js:15:1)
                    at Module._compile (module.js:570:32)
```

**Comment by garris** [comment]
Yup.  Please take a look at the `backstop-feature-tests` repo.   Take a look at the onReady script in there.   Do it like that 👍

Ping pack if you have any issues!

FWIW:  I have a task to add new examples for chromy.

**Comment by digitalpencil** [comment]
@garris that's great thanks, working fine now.
