### ISSUE TITLE
Running multiple instances (viewports) with Chromy

### ISSUE THREAD

**Issue by LanceTurri** [garris/BackstopJS#512]
Every time I run a test with the three default viewports using ChromyJS I get an error on two of the three attempts. This works perfectly on my mac side, but when I try it on windows it always fails.

**System info:**
Windows 10
Chrome Canary Version 62.0.3194.0 (Official Build) canary (64-bit) - No extensions
Running from an elevated Powershell window
BackstopJS 3.0.16 & 3.0.18

Here are the full logs with the error I am getting when executing the test:

```
PS C:\Repo\visual-regression> backstop test
BackstopJS v3.0.16
Loading config:  C:\Repo\visual-regression\backstop.json

COMMAND | Executing core for 'test'
createBitmaps | Selcted 1 of 1 scenarios.
Starting Chromy: port:9222 --window-size=320,480
Starting Chromy: port:9223 --window-size=568,1024
Starting Chromy: port:9224 --window-size=1024,768

Error: Failed to launch a browser.
    at Chromy.start$ (C:\Users\[USER_FOLDER]\AppData\Roaming\npm\node_modules\backstopjs\node_modules\chromy\dist\index.js:169:21)
    at tryCatch (C:\Users\[USER_FOLDER]\AppData\Roaming\npm\node_modules\backstopjs\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\[USER_FOLDER]\AppData\Roaming\npm\node_modules\backstopjs\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:299:22)
    
    at Generator.prototype.(anonymous function) [as next] (C:\Users\[USER_FOLDER]\AppData\Roaming\npm\node_modules\backstopjs\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:117:21)
    at tryCatch (C:\Users\[USER_FOLDER]\AppData\Roaming\npm\node_modules\backstopjs\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:65:40)
    at invoke (C:\Users\[USER_FOLDER]\AppData\Roaming\npm\node_modules\backstopjs\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:155:20)
    at C:\Users\[USER_FOLDER]\AppData\Roaming\npm\node_modules\backstopjs\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:165:13
    at <anonymous>

Error: Failed to launch a browser.
    at Chromy.start$ (C:\Users\[USER_FOLDER]\AppData\Roaming\npm\node_modules\backstopjs\node_modules\chromy\dist\index.js:169:21)
    at tryCatch (C:\Users\[USER_FOLDER]\AppData\Roaming\npm\node_modules\backstopjs\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\[USER_FOLDER]\AppData\Roaming\npm\node_modules\backstopjs\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:299:22)
    
    at Generator.prototype.(anonymous function) [as next] (C:\Users\[USER_FOLDER]\AppData\Roaming\npm\node_modules\backstopjs\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:117:21)
    at tryCatch (C:\Users\[USER_FOLDER]\AppData\Roaming\npm\node_modules\backstopjs\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:65:40)
    at invoke (C:\Users\[USER_FOLDER]\AppData\Roaming\npm\node_modules\backstopjs\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:155:20)
    at C:\Users\[USER_FOLDER]\AppData\Roaming\npm\node_modules\backstopjs\node_modules\babel-runtime\node_modules\regenerator-runtime\runtime.js:165:13
    at <anonymous>
```

**Comment by kiran-redhat** [comment]
@LanceTurri , in /core/util/runChromy.js at 165th line insert below and try:

`chromePath: "path\to\chromecanary.exe"`,

This way you are telling Chromy about chrome canary location. If this works, see if chome canary.exe is at the location where chromey is expecting to be.

**Comment by LanceTurri** [comment]
The path was correct when I went to debug, but upgrading to backstopjs 3.0.20 seems to have solved the issue. Thank you for all of the hard work!
