### ISSUE TITLE
Mismatch errors found

### ISSUE THREAD

**Issue by mig-25** [garris/BackstopJS#626]
I have created two sample projects to test out backstopjs, but I am failing on both with error of "Mismatch errors found" when I run the `backstop test` command.
After installing it globally I ran the `backstop init` command that created the backstop_data folder and its subfolders on my root.

Then I executed the `backstop test` but it returns with missmatch errors and loads the html report in the browser. But the bitmaps_test director is never created either.
On one of the sample projects I ran has the same project structure and content as the one on https://css-tricks.com/automating-css-regression-testing/ site, but using the `backstop test` instead and executing the command on the root. The scenarios code is also the same as suggested on that page. So the url path is the same as suggested on that page.

Any suggestions what I may have done wrong?

**Comment by garris** [comment]
@mig-25   Thanks for posting!  Please see this ticket — https://github.com/garris/BackstopJS/issues/518

It should resolve you’re issue.

Sorry for the inconvenience!

**Comment by garris** [comment]
@mig-25 sorry to hear it's not working.  It's hard to guess just from the information your provided.  Maybe you can look at the logs more closely for clues.   Try adding debug=true.  And try updating your version of backstop (there is a new version which provides more explicit errors)

**Comment by garris** [comment]
I just had a thought.   Did you try running `pkill -f "(chrome)?(--headless)"`

That would insure there are no zombie versions of chrome running (which can sometimes happen and cause weird failures).   Maybe that helps?

**Comment by mig-25** [comment]
I followed the same project structure as the one suggested the CSS-Tricks article <https://css-tricks.com/automating-css-regression-testing/> site, even though I used the backstop init command directly from root.
Those settings:

pkill -f "(chrome)?(--headless)"

can I directly run them from the command line? I did a new a global install again and got the following when I run backstop test:

5cg7095d27:myCoolProject sohail$ npm install -g backstopjs
/usr/local/bin/backstop -> /usr/local/lib/node_modules/backstopjs/cli/index.js
+ backstopjs@3.0.37
added 1 package and updated 3 packages in 9.869s

5cg7095d27:myCoolProject sohail$ backstop test
BackstopJS v3.0.37
Loading config:  /Users/sohail/Desktop/myCoolProject/backstop.json
COMMAND | Executing core for `test`
createBitmaps | Selected 1 of 1 scenarios.
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disa
ble-infobars=true","--window-size=320,480"],"port":9222,"waitTimeout":30000,"visible":fa
lse}Cookie state restored with: []
SCENARIO > My Local Test
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disa
ble-infobars=true","--window-size=1024,768"],"port":9223,"waitTimeout":30000,"visible":false}
Cookie state restored with: []
SCENARIO > My Local Test
9222 Chrome v63 detected.
9223 Chrome v63 detected.
      COMMAND | Executing core for `report`
      compare | Chromy error: GotoTimeoutError. See scenario – My Local Test (phone)
      compare | Chromy error: GotoTimeoutError. See scenario – My Local Test (tablet)
       report | Test completed...
       report | 0 Passed
       report | 2 Failed
       report | Writing browser report
       report | Browser reported copied
       report | Copied configuration to: /Users/sohail/Desktop/myCoolProject/backstop_data/html_report/config.js
      COMMAND | Executing core for `openReport`
   openReport | Opening report.
       report | *** Mismatch errors found ***
      COMMAND | Command `report` ended with an error after [0.088s]
      COMMAND | Error: Mismatch errors found.
                    at /usr/local/lib/node_modules/backstopjs/core/command/report.js:113:17
                    at <anonymous>
      COMMAND | Command `test` ended with an error after [31.619s]
      COMMAND | Error: Mismatch errors found.
                    at /usr/local/lib/node_modules/backstopjs/core/command/report.js:113:17
                    at <anonymous>

> 4 jan. 2018 kl. 18:10 skrev Garris <notifications@github.com>:
> 
> pkill -f "(chrome)?(--headless)"

**Comment by mig-25** [comment]
Sorry, Nothing wrong on your side, my bad, it was a path error in the url setting. I tested it out on the same project as on the CSS-Tricks article <https://css-tricks.com/automating-css-regression-testing/> page. But I changed the url path, as this time I ran the backstop init on the root and the index.html is on the root of that project.

Thanks for your help :)
