### ISSUE TITLE
Backstop/Chromy breaking when an element has position absolute css property

### ISSUE THREAD

**Issue by andrepm06** [garris/BackstopJS#656]
When a page under test has an element with position absolute property, and this element has no relative parent, Backstop or Chromy (i dont know) breaks.

Here`s the output:

`ChromyJS returned an unexpected error while attempting to capture a selector. TypeError: Cannot read property 'length' of null
    at Chromy._screenshotMultipleSelectors$ (/usr/local/lib/node_modules/backstopjs/node_modules/chromy/dist/index.js:1388:27)
    at tryCatch (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at tryCatch (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at invoke (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:152:20)
    at /usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:162:13
`

**Comment by Kenith** [comment]
same issue here ;(

```
9223 INFO >  BackstopTools have been installed.
ChromyJS returned an unexpected error while attempting to capture a selector. TypeError: Cannot read property 'length' of null
    at Chromy._screenshotMultipleSelectors$ (/usr/local/lib/node_modules/backstopjs/node_modules/chromy/dist/index.js:1388:27)
    at tryCatch (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at tryCatch (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at invoke (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:152:20)
    at /usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:162:13
    at <anonymous>
ChromyJS returned an unexpected error while attempting to capture a selector. TypeError: Cannot read property 'length' of null
    at Chromy._screenshotMultipleSelectors$ (/usr/local/lib/node_modules/backstopjs/node_modules/chromy/dist/index.js:1388:27)
    at tryCatch (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at tryCatch (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at invoke (/usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:152:20)
    at /usr/local/lib/node_modules/backstopjs/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:162:13
    at <anonymous>

Run `$ backstop test` to generate diff report.

      COMMAND | Command `reference` successfully executed in [5.41s]
ken-JSS572:Adam ken$
```

**Comment by Kenith** [comment]
@garris I tried to find a reproduce steps to you. Failed, seems only happens with certain situation

**Comment by Kenith** [comment]
@andrepm06 
Found a walkaround, set the: ```"selectors": ["body"]```
The issue gone

**Comment by garris** [comment]
Sorry for issue guys — this may be a Chromy issue.   You may want to try to repro in a Chromy-only test to rule out backstop first.
