### ISSUE TITLE
Error on COMMAND | Executing core for `report`

### ISSUE THREAD

**Issue by creaux** [garris/BackstopJS#666]
Is that possible that some dependency is missing in OS? Debian env on Heroku.

```
COMMAND | Executing core for `report`
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: Invalid file signature
    at module.exports.Parser._parseSignature (/app/node_modules/node-resemble-js/node_modules/pngjs/lib/parser.js:51:18)
    at module.exports.ChunkStream._processRead (/app/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:174:13)
    at module.exports.ChunkStream._process (/app/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:193:14)
    at module.exports.ChunkStream.write (/app/node_modules/node-resemble-js/node_modules/pngjs/lib/chunkstream.js:61:8)
    at exports.PNG.PNG.write (/app/node_modules/node-resemble-js/node_modules/pngjs/lib/png.js:92:16)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
```

**Comment by creaux** [comment]
Still have that issue there is no one dealing with this?

After update even with Backstop: v3.1.21!

**Comment by garris** [comment]
Please check the docs -- there is a sanity test that can help you figure out if your ENV/OS can run backstop...
https://github.com/garris/BackstopJS#sanity-test-does-backstop-work-in-my-enviornment

**Comment by sbaechler** [comment]
I now keep getting the same issue. Backstop used to work before in this repo.

I noticed that there are two versions of pngjs: 2.2 and 3.0. Both are transitive dependencies of Backstop.js.
