### ISSUE TITLE
"SyntaxError: Unexpected token function" when running Backstop

### ISSUE THREAD

**Issue by pbb72** [garris/BackstopJS#729]
I want to give BackstopJS a try, but I'm not getting very far. Both `backstop init` and the sanity test return the error "SyntaxError: Unexpected token function".

```
C:\temp\backstopSanityTest>node node_modules/backstopjs/cli/index.js test --config=node_modules/backstopjs/test/configs/backstop
C:\temp\backstopSanityTest\node_modules\backstopjs\core\util\runPuppet.js:38
async function processScenarioView (scenario, variantOrScenarioLabelSafe, scenarioLabelSafe, viewport, config, runId) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\temp\backstopSanityTest\node_modules\backstopjs\core\util\createBitmaps.js:10:17)
    at Module._compile (module.js:570:32)
```

I've tried with both a globally installed BackstopJS (`npm install -g backstopjs`) and locally as suggested for the sanity test. I've also installed Python 3.6.5 and that is in the Path.

I am running Windows 10 without admin rights.

**Comment by garris** [comment]
Uh oh.   I pushed a canary version out yesterday.   What version did you install?

**Comment by pbb72** [comment]
My fault, I was using an outdated Node. Updated Node, and everything seems to be running smooth now :-)

**Comment by mariovalney** [comment]
It's happening here too [BackstopJS 3.2.16].

**Comment by steigenTI** [comment]
Updated to node v8.11.4 and now it'w working.
