### ISSUE TITLE
Can not run multiple scenarios

### ISSUE THREAD

**Issue by pbb72** [garris/BackstopJS#737]
My backstop.json simply has two identical scenarios for Googles homepage, using two viewports (mobile and desktop), which should result in 4 tests.

Running with BackstopJS 3.2.11, Node 8.11.1, Windows 10 Enterprise, both normal command prompt and PowerShell.

```
{
  "id": "test-website",
  "viewports": [
    {
      "label": "mobile",
      "width": 300,
      "height": 4000
    },
    {
      "label": "desktop",
      "width": 1280,
      "height": 2000
    }
  ],
  "onBeforeScript": "chromy/onBefore.js",
  "onReadyScript": "chromy/onReady.js",
  "scenarios": [
    {
      "label": "first",
      "url": "https://www.google.com/"
    },
    {
      "label": "second",
      "url": "https://www.google.com/"
    }
  ],
  "paths": {
    "bitmaps_reference": "backstop_data/bitmaps_reference",
    "bitmaps_test": "backstop_data/bitmaps_test",
    "engine_scripts": "backstop_data/engine_scripts",
    "html_report": "backstop_data/html_report",
    "ci_report": "backstop_data/ci_report"
  },
  "engine": "chrome",
  "engineFlags": [],
  "asyncCaptureLimit": 5,
  "asyncCompareLimit": 50,
  "debug": false,
  "debugWindow": false
}
```

On rare occasions, all 4 tests are performed. But normally one, several or all tests are not performed ("Chromy error: Error. See scenario."). If some tests are not performed, then I have to manually abort the script afterwards (Ctrl+C).

```
C:\temp\backstopjs-test>backstop test
BackstopJS v3.2.11
Loading config:  C:\temp\backstopjs-test\backstop.json

COMMAND | Executing core for `test`
createBitmaps | Selected 2 of 2 scenarios.
searching for 4 available ports.
These ports will be used: [9243,9244,9246,9249]
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=300,4000"],"port":9243,"waitTimeout":30000,"visible":false}
Cookie state restored with: []
SCENARIO > first
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1280,2000"],"port":9244,"waitTimeout":30000,"visible":false}
Cookie state restored with: []
SCENARIO > first
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=300,4000"],"port":9246,"waitTimeout":30000,"visible":false}
Cookie state restored with: []
SCENARIO > second
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1280,2000"],"port":9249,"waitTimeout":30000,"visible":false}
Cookie state restored with: []
SCENARIO > second
      COMMAND | Executing core for `report`
      compare | Chromy error: Error. See scenario – first (mobile)
      compare | Chromy error: Error. See scenario – first (desktop)
      compare | Chromy error: Error. See scenario – second (mobile)
      compare | Chromy error: Error. See scenario – second (desktop)
       report | Test completed...
       report | 0 Passed
       report | 4 Failed
       report | Writing browser report
       report | Resources copied
       report | Copied configuration to: C:\temp\backstopjs-test\backstop_data\html_report\config.js
      COMMAND | Executing core for `openReport`
   openReport | Opening report.
       report | *** Mismatch errors found ***
      COMMAND | Command `report` ended with an error after [1.653s]
      COMMAND | Error: Mismatch errors found.
                    at C:\Apps\nodejs\node_modules\backstopjs\core\command\report.js:113:17
                    at <anonymous>
                    at process._tickCallback (internal/process/next_tick.js:188:7)
      COMMAND | Command `test` ended with an error after [5.905s]
      COMMAND | Error: Mismatch errors found.
                    at C:\Apps\nodejs\node_modules\backstopjs\core\command\report.js:113:17
                    at <anonymous>
                    at process._tickCallback (internal/process/next_tick.js:188:7)
Terminate batch job (Y/N)? y
```

```
C:\temp\backstopjs-test>backstop test
BackstopJS v3.2.11
Loading config:  C:\temp\backstopjs-test\backstop.json

COMMAND | Executing core for `test`
createBitmaps | Selected 2 of 2 scenarios.
searching for 4 available ports.
These ports will be used: [9243,9244,9246,9248]
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=300,4000"],"port":9243,"waitTimeout":30000,"visible":false}
Cookie state restored with: []
SCENARIO > first
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1280,2000"],"port":9244,"waitTimeout":30000,"visible":false}
Cookie state restored with: []
SCENARIO > first
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=300,4000"],"port":9246,"waitTimeout":30000,"visible":false}
Cookie state restored with: []
SCENARIO > second
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1280,2000"],"port":9248,"waitTimeout":30000,"visible":false}
Cookie state restored with: []
SCENARIO > second
9244 Chrome v68 detected.
9243 Chrome v68 detected.
9246 Chrome v68 detected.
9243 INFO >  BackstopTools have been installed.
9246 INFO >  BackstopTools have been installed.
9244 INFO >  BackstopTools have been installed.
      COMMAND | Executing core for `report`
      compare | Reference image not found test-website_first_0_document_0_mobile.png
      compare | Reference image not found test-website_first_0_document_1_desktop.png
      compare | Reference image not found test-website_second_0_document_0_mobile.png
      compare | Chromy error: Error. See scenario – second (desktop)
       report | Test completed...
       report | 0 Passed
       report | 4 Failed
       report | Writing browser report
       report | Resources copied
       report | Copied configuration to: C:\temp\backstopjs-test\backstop_data\html_report\config.js
      COMMAND | Executing core for `openReport`
   openReport | Opening report.
       report | *** Mismatch errors found ***
      COMMAND | Command `report` ended with an error after [0.245s]
      COMMAND | Error: Mismatch errors found.
                    at C:\Apps\nodejs\node_modules\backstopjs\core\command\report.js:113:17
                    at <anonymous>
                    at process._tickCallback (internal/process/next_tick.js:188:7)
      COMMAND | Command `test` ended with an error after [6.217s]
      COMMAND | Error: Mismatch errors found.
                    at C:\Apps\nodejs\node_modules\backstopjs\core\command\report.js:113:17
                    at <anonymous>
                    at process._tickCallback (internal/process/next_tick.js:188:7)
Terminate batch job (Y/N)? y
```

```
C:\temp\backstopjs-test>backstop test
BackstopJS v3.2.11
Loading config:  C:\temp\backstopjs-test\backstop.json

COMMAND | Executing core for `test`
createBitmaps | Selected 2 of 2 scenarios.
searching for 4 available ports.
These ports will be used: [9243,9244,9246,9247]
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=300,4000"],"port":9243,"waitTimeout":30000,"visible":false}
Cookie state restored with: []
SCENARIO > first
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1280,2000"],"port":9244,"waitTimeout":30000,"visible":false}
Cookie state restored with: []
SCENARIO > first
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=300,4000"],"port":9246,"waitTimeout":30000,"visible":false}
Cookie state restored with: []
SCENARIO > second
Starting Chromy: {"chromeFlags":["--disable-gpu","--force-device-scale-factor=1","--disable-infobars=true","--window-size=1280,2000"],"port":9247,"waitTimeout":30000,"visible":false}
Cookie state restored with: []
SCENARIO > second
9244 Chrome v68 detected.
9246 Chrome v68 detected.
9243 Chrome v68 detected.
9247 Chrome v68 detected.
9247 INFO >  BackstopTools have been installed.
9243 INFO >  BackstopTools have been installed.
9246 INFO >  BackstopTools have been installed.
9244 INFO >  BackstopTools have been installed.
      COMMAND | Executing core for `report`
      compare | Reference image not found test-website_first_0_document_0_mobile.png
      compare | Reference image not found test-website_first_0_document_1_desktop.png
      compare | Reference image not found test-website_second_0_document_0_mobile.png
      compare | Reference image not found test-website_second_0_document_1_desktop.png
       report | Test completed...
       report | 0 Passed
       report | 4 Failed
       report | Writing browser report
       report | Resources copied
       report | Copied configuration to: C:\temp\backstopjs-test\backstop_data\html_report\config.js
      COMMAND | Executing core for `openReport`
   openReport | Opening report.
       report | *** Mismatch errors found ***
      COMMAND | Command `report` ended with an error after [0.269s]
      COMMAND | Error: Mismatch errors found.
                    at C:\Apps\nodejs\node_modules\backstopjs\core\command\report.js:113:17
                    at <anonymous>
                    at process._tickCallback (internal/process/next_tick.js:188:7)
      COMMAND | Command `test` ended with an error after [7.603s]
      COMMAND | Error: Mismatch errors found.
                    at C:\Apps\nodejs\node_modules\backstopjs\core\command\report.js:113:17
                    at <anonymous>
                    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by KenCoder** [comment]
This looks like #724. I had the same problem and switching to puppeteer resolved it, though puppeteer is still missing some features.

**Comment by pbb72** [comment]
Thanks, the problem is solved, both with chromy and puppeteer. 😃
