### ISSUE TITLE
Using puppeteer, Chromium fails to launch when more than one scenario

### ISSUE THREAD

**Issue by ackmanx** [garris/BackstopJS#803]
I'm getting the following error if I have two scenarios in my config. The tests are opening in different tabs, instead of different instances too. One of the scenarios seems to work each time.

    BackstopJS v3.2.17
    Loading config:  /Volumes/Storage/Dropbox/Code/bookmark-express-react/backstop/backstop.scenarios.config.js
    
    COMMAND | Executing core for `test`
    createBitmaps | Selected 3 of 3 scenarios.
          COMMAND | Command `test` ended with an error after [0.776s]
          COMMAND | Error: Failed to launch chrome!
    
    
                    TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
    
                        at onClose (/Volumes/Storage/Dropbox/Code/bookmark-express-react/node_modules/puppeteer/lib/Launcher.js:285:14)
                        at ChildProcess.helper.addEventListener (/Volumes/Storage/Dropbox/Code/bookmark-express-react/node_modules/puppeteer/lib/Launcher.js:275:60)
                        at emitTwo (events.js:125:13)
                        at ChildProcess.emit (events.js:213:7)
                        at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    Browser Console Log 0: JSHandle:BackstopTools have been installed.
    Browser Console Log 0: JSHandle:connected to remotedev-server
    x Close Browser

There isn't much for an error message, but the first time this happened there was a log complaining about a file called SingletonLock existing.

My use case is a little unique, I'm testing a Chrome extension I maintain. Any idea if this is backstop, or puppeteer?

**Comment by Kenith** [comment]
Try the following...

Please go to your backstopjs install path, and find your puppeteer for example, /usr/local/lib/node_modules/backstopjs/node_modules/puppeteer

1. Edit the package.json, and replace the following version number to your number, assume your version is 999999

    ```"chromium_revision": "999999"```

2. Create your own chromium to /usr/local/lib/node_modules/backstopjs/node_modules/puppeteer:
   ```mkdir -p /usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/.local-chromium/linux-999999/chrome-linux```

3. Copy your chrome to: /usr/local/lib/node_modules/backstopjs/node_modules/puppeteer/.local-chromium/linux-999999/chrome-linux

Try to run test again....

**Comment by ackmanx** [comment]
Pointing puppeteer to a different Chromium installation produced the same error, unfortunately. 

I've narrowed the issue down to using the `--user-data-dir` switch below in the `engineOptions` property of my backstop config. If I specify a data directory source, then having more than one scenario fails entirely. If I don't specify a user directory, then I can run multiple scenarios. 

    engineOptions: {
        //These args are for Chrome/Chromium, which puppeteer uses, and are not backstop args
        args: [
            //Tell Chromium where to get its user data for each start. We need to explicitly set this so Chromium does not start with a clean (bookmarkless) profile each run
            '--user-data-dir=/Users/varr/Library/Application Support/Chromium',
        ]
    }

**Comment by ackmanx** [comment]
I might go the route of simply creating a suite of test data automatically with Chrome APIs at the start of each scenario, which should get rid of this problem. It could be a concurrency issue with multiple Chromium instances all sharing the same user data.
