### ISSUE TITLE
Docker unauthorized incorrect username or password

### ISSUE THREAD

**Issue by danielbater247** [garris/BackstopJS#913]
Trying to run --docker on a new laptop with Windows 10 and backstopjs@3.7.0
I run
`backstop test --docker`

I get
```
BackstopJS v3.7.0
Loading config:  xxx\backstop.json

COMMAND | Executing core for "test"
Delegating command to Docker... docker run --rm -it --mount type=bind,source="xxx",target=/src backstopjs/backstopjs:3.7.0 test "--moby"
Unable to find image 'backstopjs/backstopjs:3.7.0' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/backstopjs/backstopjs/manifests/3.7.0: unauthorized: incorrect username or password.
See 'docker run --help'.
COMMAND | Executing core for "openReport"
openReport | Attempting to ping
openReport | Remote not detected. Opening backstop_data\html_report\index.html
   COMMAND | Command "test" ended with an error after [0.937s]
   COMMAND | Error: docker run --rm -it --mount type=bind,source="xxx",target=/src backstopjs/backstopjs:3.7.0 test "--moby" returned 125
                 at ChildProcess.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\backstopjs\core\util\runDocker.js:36:18)
                 at ChildProcess.emit (events.js:182:13)
                 at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

Am I missing something?

**Comment by danielbater247** [comment]
Okay, should have held fire on this a little longer but, resolved with help.
https://github.com/docker/for-mac/issues/2640#issuecomment-370149492
