### ISSUE TITLE
Error capturing Element

### ISSUE THREAD

**Issue by stephanfriedrich** [garris/BackstopJS#991]
Hi, thx for your awesome tool.

I have tried to integrate your tool into an existing project. 
both the document and viewport selectors works correctly.

but i get a bug when i use a class selector in addition.
here i have bound this class (.data-testui) to the header and the footer for testing purposes.

1. *backstop reference issue*
if i now execute a ```backstop reference``` i get the following error:
```
Error capturing Element .data-testui Error: Node has 0 height.
    at assert (/opt/node/lib/node_modules/backstopjs/node_modules/puppeteer/lib/helper.js:229:11)
    at ElementHandle.screenshot (/opt/node/lib/node_modules/backstopjs/node_modules/puppeteer/lib/JSHandle.js:355:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at ElementHandle.<anonymous> (/opt/node/lib/node_modules/backstopjs/node_modules/puppeteer/lib/helper.js:108:27)
    at selectorShot (/opt/node/lib/node_modules/backstopjs/core/util/runPuppet.js:367:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```
2. *backstop test issue*
if i run the ```backstop test``` command, i get the follogin error:

```
Error capturing Element .data-testui-1 Error: Node has 0 height.
    at assert (/opt/node/lib/node_modules/backstopjs/node_modules/puppeteer/lib/helper.js:229:11)
    at ElementHandle.screenshot (/opt/node/lib/node_modules/backstopjs/node_modules/puppeteer/lib/JSHandle.js:355:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  -- ASYNC --
    at ElementHandle.<anonymous> (/opt/node/lib/node_modules/backstopjs/node_modules/puppeteer/lib/helper.js:108:27)
    at selectorShot (/opt/node/lib/node_modules/backstopjs/core/util/runPuppet.js:367:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
x Close Browser
      COMMAND | Executing core for "report"
      compare | Reference image not found testing_ui_newproject_-_Testing_UI_2_data-testui-1_0_desktop.png
      compare | OK: newproject - Testing UI testing_ui_newproject_-_Testing_UI_0_document_0_desktop.png
      compare | OK: newproject - Testing UI testing_ui_newproject_-_Testing_UI_1_viewport_0_desktop.png
      compare | OK: newproject - Testing UI testing_ui_newproject_-_Testing_UI_3_data-testui-2_0_desktop.png
      compare | OK: newproject - Testing UI testing_ui_newproject_-_Testing_UI_4_data-testui-3_0_desktop.png
       report | Test completed...
       report | 4 Passed
       report | 1 Failed
       report | Writing jUnit Report
       report | jUnit report written to: test_ui/report/ci/xunit.xml
       report | Writing browser report
       report | Resources copied
       report | Copied configuration to: /home/projects/newproject_ui-testing/src/html/test_ui/report/html/config.js
      COMMAND | Executing core for "openReport"
   openReport | Attempting to ping 
   openReport | Remote not detected. Opening test_ui/report/html/index.html
       report | *** Mismatch errors found ***
      COMMAND | Command "report" ended with an error after [0.144s]
      COMMAND | Error: Mismatch errors found.
                    at /opt/node/lib/node_modules/backstopjs/core/command/report.js:116:17
                    at <anonymous>
                    at process._tickCallback (internal/process/next_tick.js:188:7)
      COMMAND | Command "test" ended with an error after [3.229s]
      COMMAND | Error: Mismatch errors found.
                    at /opt/node/lib/node_modules/backstopjs/core/command/report.js:116:17
                    at <anonymous>
                    at process._tickCallback (internal/process/next_tick.js:188:7)
```

*System-Environment:*
* Linux Mint 19 Tara
* node: v8.9.4
* npm: 6.7.0
* BackstopJS: v3.8.8

*BTW: *
* its not a issue with overflow (because i removed every overflow style)
* its not hidden elements issue, because header and footer will be visible initial and dont have some js-related content
* especially crazy is that document and viewport test/reference images are mapped correctly

**Comment by stephanfriedrich** [comment]
my **backstop config:**

backstop.json:
```
{
  "id": "testing_ui",

  "viewports": [
    {
      "label": "desktop",
      "width": 1920,
      "height": 1080
    }
  ],

  "scenarios": [
    {
      "label": "newproject - Testing UI",
      "url": "http://localhost.hob:8105/newproject.html",
      "referenceUrl": "",

      "selectors": [
        "document",
        "viewport",
        ".data-testui"
      ],
      "hoverSelector": [

      ],
      "clickSelector": [

      ],
      "hideSelectors": [

      ],
      "removeSelectors": [
      ],

      "cookiePath": "test_ui/scripts/cookies.json",

      "readyEvent": "test_ui-ready",
      "readySelector": "html.js",

      "delay": 100,
      "postInteractionWait": 0,
      "selectorExpansion": true,
      "expect": 0,
      "misMatchThreshold" : 0.1,
      "requireSameDimensions": true
    }

  ],

  "onBeforeScript": "puppet/onBefore.js",
  "onReadyScript": "puppet/onReady.js",

  "paths": {
    "bitmaps_reference": "test_ui/images/reference",
    "bitmaps_test": "test_ui/images/test",
    "engine_scripts": "test_ui/scripts",
    "html_report": "test_ui/report/html",
    "ci_report": "test_ui/report/ci"
  },

  "report": [
    "browser",
    "CI"
  ],
  "engine": "puppeteer",
  "engineOptions": {
    "args": [
      "--no-sandbox"
    ]
  },
  "asyncCaptureLimit": 10,
  "asyncCompareLimit": 100,
  "debug": true,
  "debugWindow": false
}
```

**Comment by needpower** [comment]
Have the similar problem: when i choose `selector`:
```
{
...
scenarios: [{
  selectors: "#root"
}]
}
```
It causes an error:
`Error capturing Element #root Error: Node has 0 height.`
